hivemq/hivemq-edge

hivemq-edge/src/frontend/src/modules/ProtocolAdapters/ProtocolAdapterPage.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/AdapterController.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/15305/details/
Correct the behaviour of creating a new adapter by, upon success, opening the "Adapter List" tab

fix(15305): Creating an adapter opens the correct tabs

---

hivemq-edge/src/main/java/com/hivemq/http/filters/CorsFilter.java

Add the reissuance header to the CORS filter. see https://hivemq.kanbanize.com/ctrl_board/57/cards/15441/details/

feature (15441) - Allow JWT reissue in CORS

---

hivemq-edge/src/frontend/src/components/WarningMessage.spec.cy.tsx
hivemq-edge/src/frontend/src/components/WarningMessage.tsx
hivemq-edge/src/frontend/src/modules/Bridges/Bridges.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolIntegrationStore.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/15315/details/
The PR removes the "absolute centre" layout of the component since it centres on the whole page, regardless of the container
The fix improves the layout and the accessibility of the component, especially with a responsive design

fix(15315): Fix layout of the warning message component

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/BridgeResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/BridgeConfigurator.java

It is possible to add invalid topic filters to bridge configuration via the API (UI) which just renders the in memory bridge as dormant. When in mutable config mode, the platform then fails to start with valdiation error of the stored bridges

bug(15580): API allows invalid bridge subscribe topics to be defined

---

.github/workflows/frontend-cli.yml
hivemq-edge/src/frontend/cypress/e2e/Login/login.spec.cy.ts
hivemq-edge/src/frontend/src/components/Chakra/LoaderSpinner.spec.cy.tsx
hivemq-edge/src/frontend/src/components/Chakra/LoaderSpinner.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/Dashboard.tsx
hivemq-edge/src/frontend/src/modules/Login/LoginPage.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Login/LoginPage.tsx
hivemq-edge/src/frontend/src/modules/Login/components/Login.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/FrontendResourceImpl.java

See https://hivemq.kanbanize.com/ctrl_board/57/cards/15459/details/
The PR adds the `/api/v1/frontend/configuration` endpoint prior to the login form in order to receive, if defined, a pre-populated username and password. 
A welcome message is also added to the UI when contained in the endpoint's payload.
The post-form message ("Contact your system administrator for access credentials") is not displayed if the welcome message is given
Note that there is still a use case to decide on, whenever the user changes the prefilled values and triggers a validation error. Both welcome and error messages are displayed at the same time

feat(15459): Adding first-use username/password from configuration endpoint

---

hivemq-edge/src/frontend/src/__test-utils__/setup.ts
hivemq-edge/src/frontend/src/api/hooks/useValidationRules/useValidationRules.spec.ts
hivemq-edge/src/frontend/src/api/hooks/useValidationRules/useValidationRules.ts
hivemq-edge/src/frontend/src/config/i18n.config.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/ConnectionPanel.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/NamePanel.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/OptionsPanel.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SecurityPanel.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.tsx
hivemq-edge/src/frontend/src/modules/UnifiedNamespace/components/NamespaceForm.tsx
hivemq-edge/src/frontend/vitest.config.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/15303/details/ 
This PR changes all the React-Hook-Form forms in the web app (Bridge and Universal Names, Protocol being handled differently) so that their default values are exclusively coming from the OpenAPI specs. For example: 
``
clientId: {
type: 'string',
description: `The client identifier associated the the MQTT connection.`,
isNullable: true,
format: 'string',
maxLength: 65535,
pattern: '([a-zA-Z_0-9\\-])*',
},
``
The changes also imposed the standardisation of the error messages, for example: 
```
"validation": {
"required": "This property is required",
"maxLength": "No more than {{ count }} characters allowed for the property",
"minimum": "Should be at least {{ count }}",
"maximum": "Should not be more than {{ count }}", …
```

fix(15303): Ensure that all defaults for the forms come from the OpenAPI schemas

---

.github/workflows/frontend-cli.yml
hivemq-edge/src/frontend/.lighthouserc.cjs
hivemq-edge/src/frontend/README.md

See https://hivemq.kanbanize.com/ctrl_board/57/cards/15690/details/
The PR install Lighthouse in the `frontend` CI/CD pipeline and configure some basic gates:
- Performance = 90%
- Accessibility = 100%
- Best practice = 100%
- SEA = 100% (warning only)
See https://www.semrush.com/blog/google-lighthouse/ for a good introduction to Lighthouse
The PR also fixes the Percy integration.

chore(15690): Add Lighthouse performance testing to the pipeline

---

hivemq-edge/src/frontend/src/modules/Welcome/WelcomePage.tsx
hivemq-edge/src/frontend/src/modules/Welcome/components/Onboarding.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Welcome/components/Onboarding.tsx
hivemq-edge/src/frontend/src/modules/Welcome/hooks/useOnboarding.spec.ts
hivemq-edge/src/frontend/src/modules/Welcome/hooks/useOnboarding.tsx
hivemq-edge/src/frontend/src/modules/Welcome/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/15345/details/
This PR fixes the layout of the list of welcome task, especially when the description of the task is getting longer than a short text

fix(15345): Fix the layout of the onboarding task

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.spec.cy.tsx

Resolves [#15689](https://hivemq.kanbanize.com/ctrl_board/57/cards/15689/details/)
This PR fixes the script associated with the `Percy` GitHub action. It allows `Percy` to run in parallel both E2E and component snapshots, as defined in the `Cypress` tests: 
```js
it('should be accessible', () => {
...
cy.percySnapshot('Component: WarningMessage')
})
```
The test results are available from the `Percy` dashboard: https://percy.io/f896bbdc/hivemq-edge

fix(15689): integrate Percy pipeline

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/api/utils/ApiUtils.java
hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java

Whilst working in developer mode, it important that images render when running Frontend on a different developer server. For this reason, when specified, the developer flag will enable logoUrls to be fully qualified.

feat(16123): Ensure image URLs are served from API server

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/ModuleLoader.java
modules/hivemq-edge-module-modbus/build.gradle.kts
modules/hivemq-edge-module-opcua/build.gradle.kts

It is currently difficult to develop modules in a full runtime, due to the nature of the module loader only considering the built artefacts. Allow the build/ contributes workspace directories to be considered ahead of the lib contributed .jar files.

feat (15617) - Ensure modules are loaded from workspace in development mode

---

hivemq-edge/src/frontend/src/api/hooks/useHttpClient/useHttpClient.ts
hivemq-edge/src/frontend/src/api/queryClient.ts
hivemq-edge/src/frontend/src/config/index.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/16308/details/
This PR fixes the problem of API requests not being fired when their is no connectivity.
The main problem was with the configuration of `ReactQuery`, see documentation (https://tanstack.com/query/v4/docs/react/guides/network-mode). By default, the `Network Mode` is set to `online`, in which Queries and Mutations will not fire unless you have network connection, setting the query into a `paused` state.
The PR switches the `Network Mode` to `always`, in which Queries and Mutations are always sent and ReactQuery basically ignore online/offline status.  
The PR also introduces a `timeout` limit to all `Axios` requests (by default set to 0, implying a permanent loading).

fix(16308): Allows Edge frontend to initiate backend requests when offline 

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/ProtocolAdapterPollingServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/params/ProtocolAdapterPollingInput.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/params/impl/ProtocolAdapterPollingInputImpl.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/impl/ModbusClient.java

Added a callback hook, so that jobs who directly manage the connections through a sync API can callback and close underlying instances aligning it to the backoff job pool terminal event code path. For example when Job A exceeds its threshold and Job B shares the connection, Job A will be removed from the pool and will close the underlying resource that JobB shares - Job B will then need to be safe against bad connection handles. NOTE: The failure of Job A should NOT remove Job B by design, since Job A may have failed for a reason unrelated to the underlying connection resource, and thus Job B may still have a valid handle to work with (this becomes adapter dependant).

fix (16220) - Backed off (terminal) error jobs are not removed from pool

---

README.adoc
hivemq-edge/src/main/java/com/hivemq/configuration/reader/ArbitraryValuesMapAdapter.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java
hivemq-edge/src/test/java/com/hivemq/configuration/writer/AbstractConfigWriterTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/writer/ConfigFileWriterTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/writer/ConfigurationServiceSyncTest.java

Ensure the the arbitrary XML adapter DOES NOT wrap root instances, but DOES wrap lists with attribute names ending 's' where <> root node. Further, do not create empty elements where there exist empty lists.

fix (16221 - 16225) - Ensure the Protocol XML adapter created wrapper type correctly

---

hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/16258/details/
The PR adds the name and the icon of the protocol being edited (for both creation or modification), in the header of the side panel.
It allows the user to immediatly see which protocol the form is associated with.

feat(16258): Show which protocol the user is creating/editing and adapter for

---

hivemq-edge/src/frontend/src/api/hooks/useGatewayPortal/__handlers__/index.ts
hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/16309/details/
Add the `release version` to the main navigation bar. 
Note that the version comes from the backend `configuration` API. It will be `[ Development Snapshot ]` when running in `dev`, sometinhg like `[ 2023.5 ]` when running in `prod`

feat(16309): Add HiveMQ Edge Version number to the UI

---

hivemq-edge/src/main/java/com/hivemq/bridge/BridgeMqttClientFactory.java
hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/BridgeMqttClient.java
hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java

As a HiveMQ, we want to identify edge installations connected to our brokers, either enterprise installed on-premise or managed cloud. 
==
Example from development env:
client-agent: “HiveMQ-Edge; Development Snapshot”

fix (16316) - Set and agent value in user properties

---

hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/hooks/useGetUISchema.spec.ts
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/hooks/useGetUISchema.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/16318/details/
The PR add, through the `UISchema`, a `disabled` state to the `id` property if the adapter is modified rather than created
Notes:
- The `UISchema` is based on property names, like `id`. There it is expected that the unique identifier (or name) of an adapter is always attributed to a `id` property 
- The fix propsed in the PR needs to be tested for nested properties that might be named `id`

fix(16318): ID attribute is disabled if adapter modified rather than created

---

hivemq-edge/src/main/java/com/hivemq/HiveMQEdgeGateway.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java

OPC was reporting to stop the gateway coming up when the OPC host was unavailable. Removed the synchronous nature of the startup futures from stopping Edge starting. Also centralised management of instance creation and startup in anticipation of adapter manager refactor.

fix (16310) - Ensure OPC adapter does not block on initialisation thread

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationConfigConverter.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterFactory.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterFactory.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterUtils.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusConfigConverter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterFactory.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterFactory.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaConfigConverter.java

The XML adapter may create empty xml elements which should be treated as null by the configuration loader for the adapters. This means we need to update the interface between the core and the module system to pass in a shared preconfigured mapper which has the correct coersion settings.

fix(16313) - Use coersive manipulation of empty strings for pojo types

---

hivemq-edge/src/main/java/com/hivemq/mqtt/message/connect/MqttWillPublish.java
hivemq-edge/src/main/java/com/hivemq/mqtt/message/publish/PUBLISH.java
hivemq-edge/src/main/java/com/hivemq/mqtt/message/pubrel/PUBREL.java
hivemq-edge/src/main/java/com/hivemq/mqtt/message/subscribe/Topic.java
hivemq-edge/src/main/java/com/hivemq/persistence/IterablePersistenceEntry.java
hivemq-edge/src/main/java/com/hivemq/persistence/PersistenceEntry.java
hivemq-edge/src/main/java/com/hivemq/persistence/RetainedMessage.java
hivemq-edge/src/main/java/com/hivemq/persistence/clientsession/ClientSession.java
hivemq-edge/src/main/java/com/hivemq/persistence/clientsession/ClientSessionWill.java
hivemq-edge/src/main/java/com/hivemq/persistence/local/memory/ClientQueueMemoryLocalPersistence.java
hivemq-edge/src/main/java/com/hivemq/persistence/local/memory/ClientSessionMemoryLocalPersistence.java
hivemq-edge/src/main/java/com/hivemq/persistence/local/memory/ClientSessionSubscriptionMemoryLocalPersistence.java
hivemq-edge/src/main/java/com/hivemq/util/MemoryEstimator.java
hivemq-edge/src/test/java/com/hivemq/mqtt/message/publish/PUBLISHTest.java
hivemq-edge/src/test/java/com/hivemq/mqtt/message/pubrel/PUBRELTest.java
hivemq-edge/src/test/java/com/hivemq/persistence/local/memory/ClientQueueMemoryLocalPersistenceTest.java
hivemq-edge/src/test/java/com/hivemq/persistence/local/memory/ClientSessionSubscriptionMemoryLocalPersistenceTest.java
hivemq-edge/src/test/java/com/hivemq/util/MemoryEstimatorTest.java

**Motivation**
Add improvements for com.hivemq.util.ObjectMemoryEstimation
Resolves #https://github.com/hivemq/hivemq-edge/issues/57
**Changes**
- rename to `MemoryEstimator` (in my opinion it's a more readable name)
- remove method calls that retrieve constant values, [here](https://rules.sonarsource.com/java/RSPEC-3400/) is explained why it's better to use the constant value instead of having a function that returns a constant value
- add unit tests
- add Java doc

add improvements to com.hivemq.util.ObjectMemoryEstimation

---

hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQEdgeHttpServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQRemoteServiceImpl.java

Pings are sent directly by the HttpService. This means they were not considering the runtime configuration which was functionally considered in the layer above. We now pass an indication as to whether to start the usage tracking service through the API via contructor - which determines if the tracking engine is started.

fix(16511) - Ensure pings are NOT sent during a non-tracked runtime

---

hivemq-edge/src/main/java/com/hivemq/persistence/local/memory/ClientQueueMemoryLocalPersistence.java
hivemq-edge/src/main/java/com/hivemq/util/Strings.java
hivemq-edge/src/test/java/com/hivemq/util/StringsTest.java

**Motivation**
Method `com.hivemq.util.Strings.convertBytes` has no unit tests.
Resolves #60 
**Changes**
- rename to `toHumanReadableFormat`, I think that it's a more descriptive name
- add unit tests. 
Question. Method `FileUtils.byteCountToDisplaySize` from the commons-io library (already used in the project) does almost the same thing, more details [here](https://www.educative.io/answers/what-is-fileutilsbytecounttodisplaysize-in-java), the exception is that `FileUtils.byteCountToDisplaySize` is less precise (sizes without additional decimal points, e.g. 4 GB).
Should `com.hivemq.util.Strings.convertBytes` be deleted, and `FileUtils.byteCountToDisplaySize` be used instead?

60 - add improvements for Strings.convertBytes

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/adapters/AdapterActionMenu.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/16490/details/
This PR adds CTAs on the action menu, and inline for a highlighted adapter, to allow direct navigation to the relevant node on the workspace graph.
Note that the inline icon is temporary, only to provide immediate feedback to the user when an adapter has been created or edited. UX will need to be validated

feat(16490): Enable navigation from an adapter to its workspace node

---

hivemq-edge/src/test/java/com/hivemq/adapter/SchemaNodeGeneratorTest.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusAdapterConfig.java

The addresses on the start and end index of the modbus address are ordered alphanumerically with is incorrect. This fix allow us to specify the order to marshalled properties

Fix (16580) - Fix modbus field ordering and allow API to control natural order

---

hivemq-edge/src/frontend/src/locales/en/translation.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/16607/details/
Replace `HiveMQ` by `HiveMQ Edge`

fix(16607): fix title of the welcome page

---

hivemq-edge/src/frontend/src/api/hooks/useProtocolAdapters/__handlers__/index.ts
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/IntegrationStore/ProtocolsBrowser.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/IntegrationStore/ProtocolsBrowser.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/16528/details/
The PR hides the `create` button for adapters that are not yet installed
- filter for `installed` / `not installed` will be done in a different ticket
- handling UX (link to installation procedure or release update) will be done in a different ticket 
(no non-installed adapter on my runtime so screenshot of the Cypress test :-) )

fix(16528): Allow remote adapters to be surfaced in the catalog

---

hivemq-edge/src/frontend/src/api/hooks/useConnection/useGetAdaptersStatus.tsx
hivemq-edge/src/frontend/src/api/hooks/useConnection/useGetBridgesStatus.tsx
hivemq-edge/src/frontend/src/api/hooks/useGetBridges/useGetBridgeConnectionStatus.tsx
hivemq-edge/src/frontend/src/api/hooks/useGetBridges/useSetConnectionStatus.tsx
hivemq-edge/src/frontend/src/api/hooks/useProtocolAdapters/useCreateProtocolAdapter.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/166608/details/
An `ERROR` could be seen on the status of a new adapter, because its updated from the pooled Status request which, immediately after sending the create request, doesn't have a record for the new adapter. It gets fixed with the next call of Status
The PR utilises `ReactQuery` optimistic update to add a temporary `CONNECTING` item in the cache for the status. 
The PR also fix the ley for the request, which will also force an update of the `GET adapters` when creating a new one

fix(16608): add optimistic update of status to the creation of adapters

---

.github/workflows/frontend-cli.yml
.github/workflows/frontend-visual.yml
hivemq-edge/src/frontend/README.md
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/hooks/useGetUISchema.ts

The PR splits the frontend workflow into two: 
- `frontend-cli.yml` for the main CI/CD pipeline, running on both commits and PRs
- `frontend-visual.yml` for the Percy visual test, running on PRs only
Note that `Cypress` tests have been replicated on both pipeline, as they seem to bew required

chore(github): Split frontend pipeline for visual testing

---

hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeAdapter.tsx

The PR fixes a bug where a double click on a node doesn't open the observability panel
See  https://www.loom.com/share/6fa4ed35a40948cca811c1902cb981e1?sid=29e86280-8f09-4c90-8f95-4cf1dcd3b963

fix(2023.5): Fix double click on node

---

hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQRemoteServiceImpl.java

We are missing EDGE started events because the event was fired before initialisation, the order of which was changed in last build. Revert the order to ensure we get started events

Fix(16649) - Edge started events being missed

---

hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java
hivemq-edge/src/test/java/com/hivemq/adapter/AdapterConfigFormatTest.java

The regex passed across the API to the client should include start and tokens to demark the group boundaries of the allowed pattern.

Fix(97) - Adapter Identifier needs start and end tokens 

---

.gitignore
.idea/runConfigurations/HiveMQ_Edge___Developer.xml
.idea/runConfigurations/HiveMQ_Edge___New_Adapter.xml
hivemq-edge/src/distribution/conf/developer-config.xml
hivemq-edge/src/main/java/com/hivemq/configuration/ioc/ConfigurationFileProvider.java
hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java

Created 2 new run configuration when running in open-source project mode:
1 - Java configuration for development mode, which bootstraps the modules from your local workspace not export location
2 - Java configuration for creating a new module (CreateAdapterBlueprint#main)

Feat(92) - Add default run configurations for developer runtime and adapter creation

---

hivemq-edge/src/main/java/com/hivemq/api/model/uns/ISA95ApiBean.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/UnsResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/api/utils/ApiValidation.java
hivemq-edge/src/test/java/com/hivemq/uns/UnsModelTest.java

The API validation applied to the ISA 95 bean was flawed and did not provide anchors nor did it allow -_ or single characters. This PR updates regex(s), supplies tests and uses the correct business logic for validation.

fix(101) - UNS API validation is not aligned with UI and is flawed

---

hivemq-edge/src/frontend/cypress.config.ts
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeAdapter.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/templates/__internals/RenderFieldTemplate.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Theme/styles/FormErrorMessage.ts
hivemq-edge/src/frontend/src/modules/Theme/themeHiveMQ.ts

Fixes https://github.com/hivemq/hivemq-edge/issues/111
The PR fixes the failing tests for `color-contrast` in the accessibility pipeline. It concerns the error messages displayed below an imput field in a form. The use of ChakraUI `red.500` (#E53E3E) as a default red colour for the font failed the contrast threshold 
The PR changes the text colour to `red.600` (#C53030) and fixes a few `color-contrast` accessibility tests
(Note that the tests were not failing before because they were excluding the `color-contrast` rules)

fix(111): Fix color contrast for fields error message

---

hivemq-edge/src/frontend/src/__test-utils__/adapters/http.ts
hivemq-edge/src/frontend/src/__test-utils__/adapters/modbus.ts
hivemq-edge/src/frontend/src/__test-utils__/adapters/opc-ua.ts
hivemq-edge/src/frontend/src/__test-utils__/adapters/simulation.ts
hivemq-edge/src/frontend/src/api/types/json-schema.ts
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/topics-utils.spec.ts
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/topics-utils.ts

Fixes https://github.com/hivemq/hivemq-edge/issues/107
This PR implements routines for identifying and extracting topics from any adapters, regardless of its internals (i.e. `JSONSchema`).
The process is based on the fact that, for all the known adapters, topics are clearly identified by a custom `format` for the property. 
This is true regardless of the name and location of the `JSONSchema` property holding this information, 
The routine is based on three simple steps:
- flatten the `JSONSchema` into a list of path-defined properties
- clean the paths to isolate `mqtt-topic` and multiple items 
- recursively traverse the form data associated with the active adapter to isolate the value of the `mqtt-topic` properties
When applied to the Workspace configuration, it eliminates the need for …

feat(107): Extraction of topics from generic adapters

---

hivemq-edge/src/frontend/src/locales/en/translation.json

Fixes #125
Change the text for the namespace CTA to remove ambiguity of "setting up"

fix(125): Change namespace CTA label

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Theme/themeHiveMQ.ts

See #123
The PR change the visual aspect ofthe `STATELESS` status (for adapters) so that their "ok" status is in line with the others:
- showing `Running` instead of `Stateless`
- badge in green as with the `connected` status of other adapter
The internal status flow remains the same

fix(123): Change the text and colour of the stateless status badge

---

hivemq-edge/src/frontend/src/api/hooks/useFrontendServices/__handlers__/index.ts
hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/hooks/useGetNavItems.spec.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/hooks/useGetNavItems.tsx

See #119
Simple swap of icons. tests added

fix(119): change icon for bridge and adapter navigation menu

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/pnpm-lock.yaml
hivemq-edge/src/frontend/src/__test-utils__/react-flow/utils.ts
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/nodes-utils.ts
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/status-utils.spec.ts
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/status-utils.ts

See #123
This PR adds the proper handling of the "connection" status to the workspace following the changes made in the overall start/restart and status of the "devices" in a previous ticket.
The rendering of the links should match the colour of the status badge. As before, an animated link is rendered when there are topics defined and when the "device" is connected (status is `connected` or `stateless` and runtime `on`)

fix(123): fix status rendering on links in workspace

---

hivemq-edge/src/frontend/src/hooks/useEdgeToast/useEdgeToast.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/BridgeEditor.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17265/details/
The PR fixes one of the bugs when using the `event log`.
When accessing a bridge by clicking on the `source` link, the app navigates to the list of bridges but now checks that the required bridge exists before opening the side panel 
If it doesn't exist, an `error`  toast message is displayed

fix(17265): Check bridge existence before opening editor

---

hivemq-edge/src/frontend/src/api/hooks/useEvents/useGetEvents.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17328/details/
This PR replaces the 5s polling of the events request by a user-triggered refetch mechanism.

feat(17328): Add manual reload to the event log

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/SourceLink.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/SourceLink.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/panel/EventDrawer.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/ProtocolAdapterPage.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/AdapterController.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolIntegrationStore.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/types.ts

This PR fixes the navigation from the workspace or the event log. 
When clicking on a link to an adapter in either page, the user is now correctly navigated to the "Active Adapters" tab of the `app/protocol-adapters` page, with the editor opens whenthe source is a valide instance.

fix(17265): fix navigation to active adapter's table

---

hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.spec.cy.tsx
hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.tsx
hivemq-edge/src/frontend/src/components/PaginatedTable/components/DebouncedInput.tsx
hivemq-edge/src/frontend/src/components/PaginatedTable/components/Filter.tsx
hivemq-edge/src/frontend/src/components/PaginatedTable/utils/table-utils.spec.ts
hivemq-edge/src/frontend/src/components/PaginatedTable/utils/table-utils.ts
hivemq-edge/src/frontend/src/locales/en/components.json
hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17145/details/
This PR adds filters to selected columns of a paginated table. On a valid column, the table renders an input field that can be used to type a value to apply as a filter to the column: 
- only the rows showing the substring will be shown in the table
- a `datalist` will show the matching values that are available for select
-  All the other filterable columns act as "facets": their datalist only shows the matching values after filtering on other columns
- Each filter contains a "Clear" button that will remove the value from the filter and re-populate the table
The PR also fixes the accessibility of the column sorting, see https://hivemq.kanbanize.com/ctrl_board/57/cards/16518/details/:
- by wrapping the sortable column …

feat(17145): Add optional filtering to the paginated tables

---

hivemq-edge/src/main/java/com/hivemq/api/model/core/Payload.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java

The OPC-UA adapter had no explicit connection monitoring, it was only reactive based on subscription events. 
Remedy 
Needed to passively listen for session change notifications, along with reporting service faults (which are NOT used for session management as they could also be used for other things.

Fix (17366) - OPC - UA Background connection monitoring

---

modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterAuthTest.java

OpcUa > Fix all tests in OpcUaProtocolAdapterAuthTest. Each test had the potential to fail when the async AbstractProtocolAdapter#onStartSuccess was called before the test had finished. The onStartSuccess tries to access the field eventService which is null and throws NPE. Completing the mock fixes the flakiness.

Flaky: Fix all tests in OpcUaProtocolAdapterAuthTest.

---

modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterAuthTest.java

**Motivation**
Fixes frequent unit test failure 
**Changes**
Usage of await() instead of assertEquals()

Test-Fix: OpcUaProtocolAdapterAuthTest now handles async update of ConnectionStatus correctly

---

hivemq-edge/src/frontend/src/modules/Dashboard/components/NavLink.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/16319/details/
The PR changes the colour of the left border in the navigation panel when hovered or actived

fix(16319): Fix the colour of the links' border in the navigation panel

---

hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.tsx

see https://hivemq.kanbanize.com/ctrl_board/57/cards/17493/details/
The PR corrects the expected left alignment of the column headers on all the tables

fix(17493): Fix the alignment of the column's headers in the pafinated table

---

hivemq-edge/src/frontend/src/components/DateTime/DateTimeRangeSelector.tsx
hivemq-edge/src/frontend/src/components/DateTime/components/Option.spec.cy.tsx
hivemq-edge/src/frontend/src/components/DateTime/components/Option.tsx
hivemq-edge/src/frontend/src/components/DateTime/components/OptionBadge.spec.cy.tsx
hivemq-edge/src/frontend/src/components/DateTime/components/OptionBadge.tsx
hivemq-edge/src/frontend/src/components/DateTime/components/OptionCommand.spec.cy.tsx
hivemq-edge/src/frontend/src/components/DateTime/components/OptionCommand.tsx
hivemq-edge/src/frontend/src/components/DateTime/hooks/useRangeTranslation.spec.ts
hivemq-edge/src/frontend/src/components/DateTime/hooks/useRangeTranslation.ts
hivemq-edge/src/frontend/src/components/DateTime/types.ts
hivemq-edge/src/frontend/src/components/DateTime/utils/range-option.mocks.ts
hivemq-edge/src/frontend/src/components/DateTime/utils/range-option.utils.spec.ts
hivemq-edge/src/frontend/src/components/DateTime/utils/range-option.utils.ts
hivemq-edge/src/frontend/src/components/PaginatedTable/components/Filter.tsx
hivemq-edge/src/frontend/src/locales/en/components.json
hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17451/details/
This PR is the initial step of an evolutionary component for filtering a timestamped table by date and time. 
It aims at replicating the pattern that is now common in many timestamped systems like `DataDog` or `Sentry` by creating a modular component that provides three levels of user interaction:
- a simple context-based list of predefined time/date filters (e.g. past 5 minutes)
- access to a full date/time picker for fine-tuned data entry
- a template-based open-text component allowing fine tuning and locale-based time range definition (e.g. "yesterday" or "past 12 minutes).
In the `Event Log`: 
- the component is deployed in the paginated table as a single filter in the `Created` column, controlling a "from now to ..." …

feat(17451): add date filtering on the Event Log

---

hivemq-edge/src/frontend/cypress/support/component.tsx
hivemq-edge/src/frontend/src/api/hooks/useEvents/__handlers__/index.ts
hivemq-edge/src/frontend/src/components/DateTime/DateTimeRenderer.spec.cy.tsx
hivemq-edge/src/frontend/src/components/DateTime/DateTimeRenderer.tsx
hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.spec.ts
hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.ts
hivemq-edge/src/frontend/src/modules/EventLog/components/panel/EventDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/panel/EventDrawer.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17327/details/
The PR is an attempt at fixing the unsatisfactory display of date and time in used in the in the system. 
It is the result of an endeavour to start defining design artefacts for consistency across the different apps in the company. A relevant, in-progress, topic has been created in the design system for that purpose, see https://zeroheight.com/9c4326648/p/5495a8-date-and-time
Every date/time element in the frontend has been replaced by the unified component (in the event log and in the adapter list). As such, the PR also closes 16679 (https://hivemq.kanbanize.com/ctrl_board/67/cards/16679/details/).
The PR also closes the original attempt to trigger an external contribution for a better relative date/time, …

feat(17327): Create a consistent user-friendly rendering of Data/Time info 

---

hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.spec.ts
hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/App/routes.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/controls/NodePanelController.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx
hivemq-edge/src/frontend/src/modules/Welcome/components/Metrics.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17448/details/
This PR extends the content of the overview available in the side panel when the user clicks on one of the entities (adapter or bridge) in the workspace 
It adds a limited version of the event log:
- only showing event for the selected entity (using the filter)
- only shows the 5 most recent events
- columns restricted to the most meaningful ones
- no access to the full payload
- no pagination 
- sorting still works (but might be turned off)
A CTA allows the user to directly access the full `Event Log`, with the filter pre-populated by the selected entity's name (id)
- the payload of events is not available in the summary. The UX necessary to display it requires extended functionalities as used in the `Event Log`.

feat(17448): Add a reduced version of the event log to the overview of entities in the workspace

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/controls/NodePanelController.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeBridge.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeEdge.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeListener.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/parts/NodeNameCard.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/parts/NodeNameCard.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/parts/NodeWrapper.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17476/details/
The PR corrects a long-standing miss whereas only Adapters could be selected in the workspace and accessed the property side panel.
The PR extends the scheme to Bridges. 
Note that other entities like Edge itself or the listeners don't have any meaningful content to show in the properties so they are currently not selectable. 
The PR also fixes a few defects in the side panel: 
- improved name and type identification of the selected node
- improved layout

fix(17476): Add support for Bridge nodes in the workspace

---

hivemq-edge/src/frontend/src/components/Chakra/ClipboardCopyIconButton.spec.cy.tsx
hivemq-edge/src/frontend/src/components/Chakra/ClipboardCopyIconButton.tsx
hivemq-edge/src/frontend/src/locales/en/components.json
hivemq-edge/src/frontend/src/modules/Metrics/Metrics.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/Sample.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/Sample.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17787/details/
A small PR to improve the UX design of the copy button, which was wrongly relying on a toast to indicate success (or error) or the copy operation 
The new design follows the same pattern found in `GitHub` and other web apps. The button triggers a "loading" state to handle the asynchronous nature of the Clipboard API and display a time-limited tooltip ("Copied!").

feat(17787): refactor copy-to-clipboard component

---

hivemq-edge/src/frontend/src/components/DateTime/DateTimeRenderer.tsx
hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.spec.ts
hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.ts
hivemq-edge/src/frontend/src/locales/en/components.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17869/details/
The PR fixes the rendering of relative date/time for seconds, using the proposed design system, see https://zeroheight.com/9c4326648/p/5495a8-date-and-time
To improve readability, it changes patterns like `10 seconds ago` to `a few seconds ago` and `45 seconds ago`  to `1 minute ago`. It also fixes a bug with `in 0 seconds` for a null duration

fix(17869): Improve date/time rendering for seconds

---

hivemq-edge/src/frontend/src/components/ConnectionController/ConnectionController.spec.tsx
hivemq-edge/src/frontend/src/components/ConnectionController/ConnectionController.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Welcome/components/Onboarding.tsx
hivemq-edge/src/frontend/src/modules/Welcome/hooks/useOnboarding.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17782/details/
This PR fixes a small bug with a duplicated key in a React list (error in log, unlikely to have effect in the page itself), arising from a yet unfetched string from the API.
It also fixes the basic typography for the tasks and sections.

fix(17782): Fix duplicated keys in onboarding tasks

---

hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/controls/NodePanelController.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/LinkPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Metrics/Metrics.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/Metrics.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18003/details/
This PR is a follow-up to the main metrics initiative, see https://github.com/hivemq/hivemq-edge/pull/215. It adds persistence to the obervability panels created by the users, ensuring consistency across session. 
The persistency is done through `localStorage`, under individual keys (i.e. `edge.reports-#####`).
- There is no UI-based mechanism to clear all the metric panels, especially the orphans.

feat(18003): add localStorage for the configs of the metric panels

---

hivemq-edge/src/frontend/src/config/index.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/controls/NodePanelController.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/LinkPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Metrics/Metrics.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/Metrics.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/editor/MetricEditor.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/editor/MetricEditor.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17951/details/
This PR is a follow-up to the main metrics initiative, see https://github.com/hivemq/hivemq-edge/pull/215. It fixes problems in the metrics editor with the "expand" UX. It redesigns the component with an internal `Accordion` component and fixes layout issues.

reactor(17951): Refactor the metrics editor to a better collapsible UX 

---

hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/controls/StatusListener.tsx
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/status-utils.spec.ts
hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/status-utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18092/details/
This PR changes the way statuses are updated in the `Workspace`. Up to now, any update is relying on the re-mounting of the component every time the users navigate to the page; the list of nodes (adapter and bridges) and edges (links!) would be regenerated with the newest status. 
With the `Workspace` persistence in the workflow, this will not work anymore. 
The PR correctly "listens" to changes in the status of all the entities in the workspace, dynamically changing the graph's nodes and edges as their internal data changes. 
Note: To experience the live update (since navigating between pages will recreate the `Workspace`), open two browsers with the `Workspace` in one and the adapters in the other. Stopping/starting …

fix(18092): Fix the update of status for adapters and bridges in the wokspace

---

hivemq-edge/src/frontend/cypress/tsconfig.json
hivemq-edge/src/frontend/src/api/hooks/useFrontendServices/__handlers__/index.ts
hivemq-edge/src/frontend/src/api/hooks/useFrontendServices/useGetNotifications.tsx
hivemq-edge/src/frontend/src/api/hooks/useGitHub/__handlers__/index.ts
hivemq-edge/src/frontend/src/api/hooks/useGitHub/types.ts
hivemq-edge/src/frontend/src/api/hooks/useGitHub/useGetReleases.tsx
hivemq-edge/src/frontend/src/api/utils.ts
hivemq-edge/src/frontend/src/components/Chakra/ButtonBadge.spec.cy.tsx
hivemq-edge/src/frontend/src/components/Chakra/ButtonBadge.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.tsx
hivemq-edge/src/frontend/src/modules/Notifications/NotificationBadge.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Notifications/NotificationBadge.tsx
hivemq-edge/src/frontend/src/modules/Notifications/components/SkipNotification.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Notifications/components/SkipNotification.tsx
hivemq-edge/src/frontend/src/modules/Notifications/hooks/useGetManagedNotifications.spec.tsx
hivemq-edge/src/frontend/src/modules/Notifications/hooks/useGetManagedNotifications.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17781/details/
This PR introduces notice to the user for any new release of the system, for potential updating it.
The feature is introduced as part of the wider management of notifications in HiveMQ Edge. 
- a simple "notification" _button badge_ is added to the navigation panel, making the feature available from every point of the web application
- The _button badge_ contains a small badge indicating the number of unread notifications 
- The notifications are fetched dynamically; therefore the number displayed can change at any point in time.
- If there are no unread notifications, the _button badge_ is inactive
- When the user clicks on the _button badge_, the unread notifications are displayed as "toasts" on the right-hand side of …

feat(17781): Notification framework and new release notice

---

hivemq-edge/src/main/java/com/hivemq/HiveMQEdgeMain.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/LoggingBootstrap.java

https://hivemq.kanbanize.com/ctrl_board/42/cards/18265/details/

Register LogLevelModifierTurboFilter only once.

---

hivemq-edge/src/frontend/src/modules/Metrics/Metrics.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/container/ChartContainer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/container/Sample.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/container/Sample.tsx

fix(18218): Fix the availability of the "remove metrics" button for Stats
See https://hivemq.kanbanize.com/ctrl_board/57/cards/18218/details/
This PR fixes a small oversight: a `Stat` chart (the simple value and increase/decrease indicators) could still be removed from a panel even if the editor was "collapsed".
This was a breach of the design pattern applied to the other charts. Charts cannot be edited or removed from the panel unless the editor is "expanded" and ready for usage.

fix(18218): Fix the availability of the "remove metrics" button for Stats

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/src/modules/Workspace/components/ReactFlowWrapper.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/NodeWrapper.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/reactflow-chakra.fix.css

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18246/details/
This PR fixes a long-standing accessibility issue with the custom nodes in the graph. 
Their `selected` and `focus-visible` statuses are now properly materialised by the similar blue shadow box used for all the other widgets in the UI.
In the graph, it means that nodes (`HiveMQ Edge`, `Adapter`, `Bridge` and `Group`) and the edge's observability button are now properly rendered and responding to keyboard navigation.
- the side panel for the interactive elements is still based on a double-click, which is not keyboard-friendly. It will be fixed in a separate PR.

fix(18246): fix focus/selected status of nodes in workspace

---

hivemq-edge/src/frontend/src/modules/Workspace/components/ReactFlowWrapper.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/controls/GroupNodesControl.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeBridge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeEdge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeGroup.tsx
hivemq-edge/src/frontend/src/modules/Workspace/hooks/useWorkspaceStore.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/hooks/useWorkspaceStore.ts
hivemq-edge/src/frontend/src/modules/Workspace/types.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/group.utils.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/group.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18204/details/
This PR improves the computation of the initial location of a group and, at its deletion, of its nodes.
The changes guarantee that, when a group is created, the selected nodes remain at the same visual position on the canvas. Similarly, when the nodes are ungrouped, their visual positions remain the same on the canvas. when the group is deleted. 
The new implementation ensures that repetitive grouping and ungrouping don't introduce any "drift" on the visual canvas.
The PR also fixes two visual aspects of nodes on the graph:
- the "edge handles" (used to connect nodes by an edge) are now properly "not manually connectable" and prevent the rendering of a "preview" of an edge when clicking and dragging
- the rendering of a …

fix(18204): Refactor the location of a group and its nodes

---

hivemq-edge/src/frontend/src/components/Chakra/ColorPicker.spec.cy.tsx
hivemq-edge/src/frontend/src/components/Chakra/ColorPicker.tsx
hivemq-edge/src/frontend/src/locales/en/components.json
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Workspace/components/controls/GroupNodesControl.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeGroup.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/GroupMetadataEditor.tsx
hivemq-edge/src/frontend/src/modules/Workspace/hooks/useWorkspaceStore.ts
hivemq-edge/src/frontend/src/modules/Workspace/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18214/details/
This PR adds a simple editor to the group's side panel, allowing users to change the two pieces of information defined by its creation: title and colour scheme.
The editor follows the same pattern as the metrics editor, with a simple collapsible panel with the form.
The colour scheme input is a `Colour Picker` designed to work with the default schemes defined within the `Chakra UI` theme. The number of colours added to the pickers is customisable. 
As with defining a `colourScheme` for other components, the scheme selected for the group will use the two hues `.100` and `.500` for the background and the border respectively

feat(18214): Add editor for the group metadata

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Workspace/components/edges/MonitoringEdge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeBridge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeGroup.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeGroup.tsx
hivemq-edge/src/frontend/src/modules/Workspace/hooks/useContextMenu.spec.tsx
hivemq-edge/src/frontend/src/modules/Workspace/hooks/useContextMenu.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18293/details/
This PR changes the keyboard and mouse interaction with the nodes (adapters, bridges and groups) on the workspace. 
- a double click on a node opens the `Overview` side panel (before/after)
- a right-click on a node opens the `Overview` side panel  (after)
- a click on the icon on a link opens the `Observability` side panel of the source node (before was double-click)
- `Meta + Enter` with a node selected opens its `Overview` side panel
- `Shift + Enter` with a node selected opens its `Overview` side panel
The default keys and mouse events from `ReactFlow`  for manipulating nodes and the canvas are still in operation.
The PR also adds a link to the panel in the group's toolbar.

fix(18293): Change mouse and keyboard interactions with nodes

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/src/api/__generated__/models/LocalBridgeSubscription.ts
hivemq-edge/src/frontend/src/api/__generated__/schemas/$LocalBridgeSubscription.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17823/details/
This PR adds a new "queue limit" field to the local subscription form. 
It is part of the persistence feature and the field has conditions:
- if `mqtt-persistence` is not part of the Edge capabilities, the field is no shown
- if the `persist` flag is not turned on, the field is disabled
- if the `maxQoS` for the subscription is set at 0, the field is disabled 
- The range of valid numbers for the limit is undefined. Users could set any number from 10s to millions of messages. With no default, the initial value will be treated at 0. Using the UI "helpers" for number fields (spinners and mouse wheel) cannot deliver supportive behaviour unless an appropriate "step" is defined (e.g. increment by 1000s). The default increment …

feat(17823): Add form field for the limit of persisted queue message

---

hivemq-edge/src/frontend/src/modules/Workspace/utils/status-utils.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/status-utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18216/details/
This PR fixes the computation of the summarised status as displayed on the single edge when the group is collapsed 
In an "expanded" view, each one of the grouped nodes still shows its own edge to the `Edge` node. When collapsed, the group node summarises all the edges into a single one connecting it to the `Edge`. 
Its status is based on the union of all the included nodes:
- if one of the nodes is `STOPPED` then the group's status will be `STOPPED`
- if one of the nodes is `DISCONNECTED` then the group's status will be `DISCONNECTED`
- if one of the nodes has no topic, then the group's edge will be shown as `DATA NOT FLOWING`
The purpose is to convey a summary of the group of nodes by singling out the `DISCONNECTED` and …

fix(18216): Fix the propagation of status to a collapsed group's edge

---

hivemq-edge/src/frontend/src/modules/Metrics/Metrics.tsx
hivemq-edge/src/frontend/src/modules/Metrics/hooks/useMetricsStore.spec.ts
hivemq-edge/src/frontend/src/modules/Metrics/hooks/useMetricsStore.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeGroup.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18161/details/
This simple PR is removing the direct use of the `localStorage` to a cleaner and more versatile state-management solution (`Zustand`).vanch

refactor(18161): Change the persistence of the metrics to a local store

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Metrics/Metrics.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/charts/BarChart.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/charts/BarChart.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/charts/LineChart.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/charts/LineChart.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/charts/SampleRenderer.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/container/ChartContainer.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/container/Sample.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/parts/ChartTooltip.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/parts/ChartTooltip.tsx
hivemq-edge/src/frontend/src/modules/Metrics/types.ts
hivemq-edge/src/frontend/src/modules/Theme/styles/Stat.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/controls/NodePanelController.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18077/details/
The PR refactors the charts in the Observability panel, in order to alig ntheir design with the theme used for the Edge application. 
- The color schemes for the "series" are now based on the `ChakraUI` theme
- each data series in a chart is assign one of the available color scheme
- the tooltip is now consistent across the line and bar charts 
- the legend of the line and barcharts are now properly disaplyed
- the x-axis of the line and chart is now using a proper timestamp formatttng 
The PR also fixes the nature of the group side panel, properly differentiating between "Overview" and "Observability", as for the other nodes.
- The display of multiple series within a chart will be dealt with in another ticket. See …

refactor(18077): Align the design of the charts with the Edge theme

---

hivemq-edge/src/frontend/src/modules/Bridges/components/panels/PersistencePanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/PersistencePanel.tsx
hivemq-edge/src/frontend/src/modules/Bridges/hooks/useBridgeConfig.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17823/details/
Small PR to fix the following issue
- default `persist` option set to checked on creation
- restart warning message removed from the UI

fix(17823): Change persist default and remove warning

---

hivemq-edge/src/frontend/src/__test-utils__/msw/handlers.ts
hivemq-edge/src/frontend/src/__test-utils__/react-flow/nodes.ts
hivemq-edge/src/frontend/src/api/hooks/useFrontendServices/useGetCapability.tsx
hivemq-edge/src/frontend/src/config/i18n.config.ts
hivemq-edge/src/frontend/src/extensions/datahub/components/DataHubPage.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CanvasControls.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CanvasControls.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/Minimap.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/Minimap.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/PropertyPanelController.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/PropertyPanelController.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/NodeIcon.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/NodeIcon.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/BaseNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/BaseNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/NodeWrapper.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/hooks/useDataHubDraftStore.ts
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/routes.tsx
hivemq-edge/src/frontend/src/extensions/datahub/types.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts
hivemq-edge/src/frontend/src/modules/App/routes.spec.tsx
hivemq-edge/src/frontend/src/modules/App/routes.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/hooks/useGetNavItems.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18687/details/
This PR is part of the `DataHub` frontend initiatives and creates the basic elements for the integration with Edge: 
- in-app navigation and menus to enable the feature at the interface
- landing page
- initial flow canvas with basic node and side editor for the nodes in the canvas
The design reuses many of the principles in place in the `Workspace`:
- canvas showing a graph composed of nodes and edges
- user interactions on the canvas (pan, scroll, ...)
- user interactions on the graph elements
- custom rendering of the graph elements 
- When `datahub` is not activated, a simple warning message is displayed. A better UX will be added at a later stage
- The content (nodes) and flow (layout) of the policies will be added …

feat(18687): Add navigation and basic flow architecture

---

hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/ReactFlowSchemaForm.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/BehaviorPolicyPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/ClientFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/TopicFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/ValidatorPanel.spec.cy.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18840/details/
The PR changes the default heading used for titles in the JSONSchema form to `h2`.
It fixes an accessibility issue with the heading preferred to be incremented by 1 on nesting (the previous value was `h5`).

refactor(18840): Change the heading for titles in the node forms

---

hivemq-edge/src/frontend/src/extensions/datahub/components/controls/PropertyPanelController.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/PropertyPanelController.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/ReactFlowSchemaForm.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/BehaviorPolicyPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/ClientFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/OperationPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/SchemaPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/TopicFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/TransitionPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/ValidatorPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18855/details/
This PR fixes a usability problem whereas a scrolling form would hide the `submit` button at the bottom of it. It is now located on the "sticky" footer of the side panel, always visible to the user. This new behaviour is the same for the adapter forms.
The PR also slightly improves the layout of the generated JSONSchema form, reducing the amount of unnecessary nesting of "group".

refactor(18855): Relocate the submit button to the footer of the panel

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/pnpm-lock.yaml
hivemq-edge/src/frontend/src/extensions/datahub/api/specs/DataPolicyValidator.ts
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/BaseNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/BehaviorPolicyNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/BehaviorPolicyNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/ClientFilterNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/ClientFilterNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/CustomHandle.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/CustomHandle.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/DataPolicyNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/DataPolicyNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/OperationNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/OperationNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/SchemaNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/SchemaNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/TopicFilterNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/TransitionNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/TransitionNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/ValidatorNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/ValidatorNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.module.scss
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/types.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18842/details/
This PR complements the work done on the new visual language for policies by adding and visualising constraints between elements on the canvas.
The PR also fixes a few styling issues with the nodes.
- The two types of handles on nodes have been made more visible to highlight `target` (circle) and `source` (square) 
- Connecting two nodes can only be done between a source and a target. Drag-and-drop can be used from any direction but the created link will be directional.
- A source node can only be connected to a valid target. Each node defined its own validity (e.g. `Topic Filter` connected to `Data Policy` only)
- Some nodes (e.g. `Data Policy` or `Operation`) also have cardinality constraints and only allow one link to …

feat(18842): Implement connectivity controls between the different types of node

---

hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/OperationData.json
hivemq-edge/src/frontend/src/extensions/datahub/api/specs/OperationData.ts
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/FunctionNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/OperationNode.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/OperationNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/types.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts
hivemq-edge/src/frontend/tsconfig.json
hivemq-edge/src/frontend/vite.config.ts
hivemq-edge/src/frontend/vitest.config.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18991/details/
This PR changes the UX for the `DataHub.transform` Operation definition to add the `deserialiser` and `serialiser` handles to the node. It allows the pipeline not to have to explicitly use the two dedicated nodes and makes the abstraction more meaningful to the users. It also changes the schema, to allow multiple functions to be added.
The API payload is not changing: the node will be converted to the three individual actions when submitted.

refactor(18991): Refactor "Transform" Operation to include serialisers

---

hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/TopicFilterData.json
hivemq-edge/src/frontend/src/extensions/datahub/api/specs/TopicFilterData.ts
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/AdapterSelect.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/AdapterSelect.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/EditorWidgetRegistry.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/TopicFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/panels/TopicFilterPanel.tsx
hivemq-edge/src/frontend/src/extensions/datahub/types.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/edges/MonitoringEdge.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18844/details/
This PR creates the first step in allowing the users to naturally navigate between the core functionality of `Edge` and `DataHub`
The `Topic Filters` element of the data policy flow now accepts an optional `Adapter` in the configuration panel. The select widget contains the list of all live adapters and can be searched for instances. 
Once selected, two extra features will be enabled: 
- in the `Workspace`, the link that connects this adapter to `Edge` will now contain a second icon, which allows users to navigate to the `DataHub` sketch directly, selecting the relevant node
- in the `Topic Filters` configuration panel, the list of strings now runs an extra validation step: if the edited topic filters don't match one of …

feat(18844): Add a simple UX connection between Edge and DataHub

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SecurityPanel.tsx

Added definition for cipher Suite placeholder text in i18n bundle and utilised bundle in the form component.

fix(19439) - CipherSuite placeholder text fix

---

hivemq-edge/src/main/java/com/hivemq/bridge/metrics/PerBridgeMetrics.java
hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/BridgeMqttClient.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/metrics/ProtocolAdapterMetricsHelper.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
hivemq-edge/src/test/java/com/hivemq/adapter/ProtocolMetricsHelperTest.java
hivemq-edge/src/test/java/com/hivemq/bridge/BridgeMetricsTest.java

**Motivation**
**Changes**
When a bridge is stopped / deleted, the associated metrics are removed.
When an adaper is updated / deletedthe associated metrics are removed.

fix(17211) - Cascase bridge and adapter metrics on delete / stop

---

hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubSchemasService/__handlers__/index.ts
hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubScriptsService/__handlers__/index.ts
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxPublish.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DataHubListAction.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/transition/TransitionNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/transition/TransitionNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/19819/details/
The PR adds the confirmation dialogue to the deletion of items in the `policy`, `script` and `schema` tables, to ensure deletion doesn't occur by mistake (they are non-reversible). 
Upon confirmation, the usual toast confirms the deletion of the item or shows any error.

feat(19819): Add safeguard and feedback to the deletion of items in the data hub tables

---

hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/modules/Dashboard/hooks/useGetNavItems.spec.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/hooks/useGetNavItems.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/19826/details/
The PR reorganise the main navigation menu of Edge
- Extension section removed
- Main links reorderer
- Change name to `Data Hub on Edge`

refactor(19826): Cleanup the menu of HiveMQ Edge

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/pnpm-lock.yaml
hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/SchemaData.json
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaPanel.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/validation.errors.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20139/details/
The PR fixes a few bugs with the text version of PROTOBUF in the `Schema` node and its side panel. 
A field for selecting the active message has been added to the JSON Schema of the PROTOBUF configuration. 
Validation of the code and error reporting are now supported. 
The PROTOBUF code is now compiled to a descriptor buffer and then encoded to a `base64` fully on the browser side. It means the end-user has access to the full flow of PROTOBUF schemas, from the editing (or copy-and-paste) to the validation, then to the submission to the backend, then to the listing of created schemas, then finally to the modifying of the original code. 
The client-side encoding relies on a self-described experimental feature of the …

refactor(20139): Add validation and error handling for PROTOBUF code

---

hivemq-edge/src/frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/hooks/usePolicyDryRun.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20147/details/
The PR fixes a bug with the check of `Data Policies`, which is now accepting them to be without any explicit validation. 
It also fixes translations, in particular the `Dat Hub` navigation menu

fix(20147): allow data policy to be created without validators

---

hivemq-edge/src/frontend/src/extensions/datahub/components/forms/MetricCounterInput.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20145/details/
The PR fixes the placeholder for `JS Function` in the `Operation` side panel.

fix(20145): Fix placeholder for function

---

hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/FunctionData.json
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DesignerToolbox.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxNodes.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DraftCTA.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DraftStatus.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditorLoader.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/hooks/useDataHubDraftStore.ts
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/types.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/store.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/store.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20275/details/
The PR clarifies the status of the Data Hub Designer when dealing with draft or loaded/modified policies. 
- A `status` is added to the `Data Hub store, indicating whether the canvas contains a `DRAFT`, a `LOADED` policy or a `MODIFIED` policy.
- An info panel is added to the toolbar, indicating the `status` of the Designer's canvas and, if appropriate, the name and type of a loaded policy
- The primary CTA on the policy table changes state depending on the `status` (Create a new policy, Continue on draft, Clear the draft)
The PR also improves several aspects of the UX
- The texts in the toolbar cannot be selected by the user; it improves usability
- The Designer building buttons are disabled until a `data policy` or …

feat(20275): Improve the UX flow for draft and edited policy

---

hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxDryRun.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxNodes.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxPublish.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DataHubListAction.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DataHubListAction.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DraftStatus.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/utils/date.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/download.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20401/details/
The PR adds two features allowing a partial release of the `Data Hub Designer`:
- the payload of the `policies`, `scripts` and `schemas` can be downloaded from the main tables. The JSON is exported and minified in a file automatically named from the `id` of the object and the timestamp of the download.
- access to the canvas of a saved policy is through a "view" command rather than the previous "edit". The canvas can still be explored, manipulated (and, unfortunately, modified) but it cannot be checked or published
The PR also fixes a small issue with the "clearing the canvas" action by navigating back to the right location.

feat(20401): Support downloading payloads and read-only canvas

---

hivemq-edge/src/frontend/src/components/Modal/ConfirmationDialog.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/WorkspaceOptionsDrawer.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18854/details/
The PR adds a `reset` option to the `workspace` configuration panel, allowing users to clean any discrepancies between the content of the workspace and the Edge topology.
The issue arises from aspects of the workspace visualisation being persisted on the `localStorage` of the browser but occasionally being dissociated from the elements (i.e. adapters and bridges) effectively known to the Esge system. 
The manual reset will help with that situation but many aspects of the user personalisation of the workspace being lost: location of the nodes on the graph, groups created, configuration of the analytics panel. 
Confirmation is required before resetting. The user will be navigated back to the main, to action the reset. The …

feat(18854): Add reset to the workspace

---

hivemq-edge/src/frontend/src/modules/ProtocolAdapters/hooks/useGetUISchema.ts
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/ProtocolAdapterDataSample.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/model/HttpData.java
modules/hivemq-edge-module-http/src/test/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterTest.java

**Motivation**
Resolves #18091
I have added a new checkbox “Assert JSON Payload” which, when checked will always attempt to parse the payload as JSON regardless of the content type on the response object. I considered using a dropdown with multiple content types for the response, but actually the reality is that it will almost always be either dynamic (existing behaviour) OR JSON.
**Changes**

Fix(18091) - Payload in HTTP adapter

---

hivemq-edge/src/frontend/src/extensions/datahub/components/forms/MetricCounterInput.tsx

Fixes the prefix for metric names in the UI to `com.hivemq.edge`

Fix metric name prefix

---

hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxNodes.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/forms/MessageInterpolationTextArea.tsx

The PR hides the client filter button from the toolbar and the interpolation buttoins from the `Sytem.log` operation configuration panel 
They are hidden for the current release behind two internal feature flags

fix(hotfix): Remove client filter and interpolation for the release version

---

hivemq-edge/src/frontend/src/extensions/datahub/components/DataHubPage.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/DataHubPage.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/LicenseWarning.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/LicenseWarning.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20325/details/
The PR updates the rendering of the license warning message. The message is streamlined and the "contact us" links to the  https://www.hivemq.com/contact/ page

refactor(20325): Improve the license warning

---

.github/workflows/frontend-cli.yml
.github/workflows/frontend-visual.yml
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/PropertyPanelController.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/topic_filter/TopicFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/overview/BridgeCard.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Notifications/NotificationBadge.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/NodePropertyDrawer.spec.cy.tsx

In the `CI` pipeline, the output of the `Cypress` was very verbose (more than 35K lines in the stdout). This was mostly due to every API request not being used by the tests, to not be intercepted by Cypress, resulting in an ECONNREFUSED error which dumped the whole request message in the stdout. A lot of noise masking the details of errors in the tests. 
An option to disable `morgan` outputs (see https://github.com/cypress-io/cypress/issues/26284#issuecomment-1498191390) didn't seem to be working with the GitHub actions
```
Warning: Unexpected input(s) 'morgan', valid inputs are ['record', 'auto-cancel-after-failures', 'config', 'config-file', 'env', 'browser', 'command', 'start', 'start-windows', 'build', 'install', 'install-command', 'runTests', 'wait-on', 'wait-on-timeout', 'parallel', …
```

chore(CI): reduce verbosity of cypress output

---

.github/workflows/frontend-cli.yml
.github/workflows/frontend-visual.yml
hivemq-edge/src/frontend/cypress/e2e/Login/login.spec.cy.ts
hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/pnpm-lock.yaml
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/PropertyPanelController.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/topic_filter/TopicFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/overview/BridgeCard.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Notifications/NotificationBadge.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/NodePropertyDrawer.spec.cy.tsx

The PR reverts dependencies changes (#339) that created errors with the CI test pipeline. 
It updates `vite` and `axios`  as per `renovate` (closes #332 and #331 ).
It re-injects #340.

chore(dependencies): fix dependencies (vite/axios) and update cypress

---

hivemq-edge/src/main/java/com/hivemq/http/JaxrsHttpServer.java
hivemq-edge/src/test/java/com/hivemq/api/JaxrsResourceTests.java
hivemq-edge/src/test/java/com/hivemq/api/JaxrsSSLTests.java
hivemq-edge/src/test/java/com/hivemq/api/auth/BasicAuthenticationTests.java
hivemq-edge/src/test/java/com/hivemq/api/auth/BearerTokenAuthTests.java
hivemq-edge/src/test/java/com/hivemq/api/auth/ChainedAuthTests.java

**Motivation**
Resolves #285 
**Changes**
Log the port and URI in case the HttpServer start fails
No change in further error handling to avoid a silent fail

Improve Logging in case Binding Port of API Server is already in use.

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/AdapterDataUtils.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/ProtocolAdapterDataSample.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/config/impl/AbstractProtocolAdapterConfig.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModBusUtils.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusAdapterConfig.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-modbus/src/test/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterTest.java

When the checkbox only publish data items that have changed since last poll was set, the entire previous graph (which may have contained multiple indices) was sent with each poll if a single items had changed. The calculation now considered each item individually.

fix(19348) - Modbus change data calculation should only publish deltas

---

hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20074/details/
The PR fixes the tooltip of the button icon in the protocol adapter table,

fix(20074): Fix the tooltip

---

hivemq-edge/src/frontend/src/modules/Bridges/components/panels/OptionsPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/OptionsPanel.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/19238/details/
The PR fixes the two checkboxes in the Brodge form that are constantly checked out at the initial opening of the form, regardless of their values

fix(19238): Fix the default cleanStart checkbox

---

hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/BehaviorPolicyData.json
hivemq-edge/src/frontend/src/extensions/datahub/components/forms/TransitionSelect.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/forms/TransitionSelect.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/transition/TransitionNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/transition/TransitionPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/transition/TransitionPanel.tsx
hivemq-edge/src/frontend/src/extensions/datahub/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/21032/details/
The PR improves the rendering of a `behaviour policy` by highlighting, when appropriate, the terminal status of a transition. 
The highlight is materialised by a `success` or `failure` handle of the `Transition` node and, by doing so, aligns with a similar status materialised for the `data policy` 
The PR also adds `success` disconnected transitions that are missing from the generated model.
- The rendering of the `transition` node only shows the transition name, not the end state of the FSM. It certainly creates ambiguity, since the transition names are not unique. Guards, indicating further conditions to the application of the transition, will be added in a future ticket, ensuring unicity of names.

refactor(21032): Add status of terminal transitions to the node

---

.github/workflows/frontend-cli.yml
hivemq-edge/src/frontend/.prettierignore
hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/FunctionData.json
hivemq-edge/src/frontend/src/extensions/datahub/components/forms/ResourceNameCreatableSelect.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/forms/ResourceNameCreatableSelect.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/datahubRJSFWidgets.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaPanel.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionData.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionPanel.tsx
hivemq-edge/src/frontend/src/extensions/datahub/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20712/details/
This PR replicate the editing flow of the `Schemas` (see #334 ) to the `Scripts`. The same states and transitions are applied to the elements of the editing form (name, version and description + source ). 
```mermaid
stateDiagram-v2
[*] --> DRAFT: create
[*] --> VERSION_N: load
DRAFT --> DRAFT: select type
DRAFT --> DRAFT: edit content
DRAFT --> DRAFT: create new name
DRAFT --> VERSION_LATEST: select name
VERSION_N:::namedSchema --> VERSION_LATEST: select name
VERSION_N --> DRAFT: create new name
VERSION_LATEST:::namedSchema --> DRAFT: create new name
VERSION_LATEST --> VERSION_N: select version
VERSION_N --> VERSION_N: select version
VERSION_LATEST --> MODIFIED: edit content
VERSION_N --> MODIFIED: edit content
DRAFT --> …
```

refactor(20712): update the edit flow for the Scripts

---

hivemq-edge/src/frontend/src/extensions/datahub/components/interpolation/Editor.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/interpolation/Suggestion.ts
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SubscriptionsPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20433/details/
AJV8, used to validate the JSONSchema form, generates a "no schema with key or ref" error which is displayed at the first load of an adapter. It has not been possible to fix the error. 
The PR filters the message out of the list to be displayed on the summary. 
Note that the generated error message has no other identifier in the payload, except the "stack" attribute.

fix(20433): Remove Schema Ref message from the list

---

hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxNodes.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxNodes.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/checks.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/transition/TransitionNode.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/21115/details/
The PR re-enables the behaviour policies in the `Data Hub Designer` and fixed two bugs with the loading of payload:
- terminal status of the transitions is computed properly
- improve the automatic layout of the transition

fix(21115): re-enable behaviour policy

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.tsx
hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/OperationData.json
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxDryRun.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/PolicySummaryReport.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/checks.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/hooks/usePolicyDryRun.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/hooks/usePolicyDryRun.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/datahub.utils.ts
hivemq-edge/src/frontend/vitest.config.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20360/details/
The PR fixes the publishing process of multiple scripts in a transformation node. The current process was only saving the first script connected to the `Operation` node. 
The PR also slighlty improves the rendering of the successful report on a `dry run` and the default layout for (multiple) schemas and scripts.

fix(20360): Fix the serialisation of multiple scripts

---

hivemq-edge/src/frontend/src/components/PaginatedTable/components/PaginationBar.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/19388/details/
The PR fixes the bug in the pagination toolbar, which had all the icons identical. It also updates all icons to the Lucide set.

refactor(19388): Fix the icons of the table pagination toolbar

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/pnpm-lock.yaml
hivemq-edge/src/frontend/src/components/Chakra/ShortcutRenderer.spec.cy.tsx
hivemq-edge/src/frontend/src/components/Chakra/ShortcutRenderer.tsx
hivemq-edge/src/frontend/src/extensions/datahub/__test-utils__/MockStoreWrapper.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CanvasControls.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CanvasControls.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CopyPasteListener.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CopyPasteListener.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CopyPasteStatus.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CopyPasteStatus.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DesignerCheatSheet.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DesignerCheatSheet.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/types.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/datahub.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/21481/details/
This PR improves the UX of the `Data Hub Designer` by allowing users to copy nodes from the graph and duplicate them as new elements. 
The operation is an internal "copy-and-paste" of the selection in the designer:
- one or many nodes can be selected manually from the graph  
- on "copy", the subgraph containing the selected nodes (i.e. including all the edges that have both start and end nodes in the selection) is duplicated (i.e. new id, new shifted position but the same configuration of the nodes
- on "paste", the new nodes are added to the graph but not connected to existing nodes. 
- subsequent "paste" will duplicate the selected nodes in a shifting pattern on the graph, allowing multiple duplications
- "copy" is …

feat(21481): Add node duplication and copy-and-paste support

---

hivemq-edge/src/frontend/src/components/Chakra/ShortcutRenderer.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/21625/details/
The PR prevents cycles from being created in the Designer when connecting nodes either to themselves or back to the beginning of a chain. 
This is the case exclusively of the `OPERATION` node, as being the only content that can be chained.

fix(21625): Prevent cycles in the Designer graphs

---

hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/ConnectionLine.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicyNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/types.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/21481/details/
This PR enables the creation of nodes directly from the dropping of an edge created from a source node onto the canvas. 
The action is based on the strong typing of the connection between different nodes: it is possible, by starting an edge from the handle of a node to know what target node is expected, therefore unambiguously creating it when the user drops the edge
Notes
- The drop of the edge MUST happen on the canvas itself, away from other nodes and edges
- The process is bidirectional, either from the "source" or "target" handle of any node; the direction of the created edge will be properly defined 
- A few nodes (SCHEMA, specific instances of OPERATION) are ambiguous and therefore don't support the create-on-drop. …

feat(21481): Create nodes from dropping an edge from a source

---

hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxNodes.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxNodes.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/19310/details/
Fix the translations for the app, focusing on the `EN-US` language. 
Changed the label for the first group of icons in the Designer toolbox, to reflect the focus on integration between `Data Hub` and `Edge`.

fix(19310): Improve Data Hub translations

---

hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/NodeWrapper.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditorLoader.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicyNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/client_filter/ClientFilterNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/data_policy/DataPolicyNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/topic_filter/TopicFilterNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/transition/TransitionNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/hooks/useDataHubDraftStore.spec.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Workspace/hooks/useWorkspaceStore.spec.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20321/details/
The PR refactors how the policy payload is transformed into a designer graph. 
The previous process was creating the graph elements (nodes and edges) from the payload and inserting them iteratively into the Design store. This created a re-render race condition, with parent nodes not yet inserted into the graph when their connecting edges were added. The error message at the first loading was the visual result of the faulty operation. 
The new process iteratively creates ALL the graph elements BEFORE inserting them in two distinct operations: nodes first then edges. 
The PR also fixes a bug with the behaviour policy, in which pipelines were connected to every transition created, regardless of the real dependency.

refactor(20321): Refactoring the policy loading 

---

hivemq-edge/src/frontend/src/extensions/datahub/designer/client_filter/ClientFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/topic_filter/TopicFilterPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/topic_filter/TopicFilterPanel.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/20611/details/
The PR adds a custom validator to the `Topic Filter` configuration panel, ensuring that the filter added to a data policy is not already in use in another policy. Note that the check is purely syntactic on the filter itself, not on the topics it migth match.

feat(20611): Add uniqueness validation to topic filter

---

hivemq-edge/src/frontend/src/locales/en/components.json
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/ProtocolAdapterPage.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/ProtocolAdapterPage.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/templates/ArrayFieldItemTemplate.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/hooks/useGetUISchema.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/edges/ObservabilityEdgeCTA.spec.cy.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/19269/details/
This PR enables items in an array-based property of a `JSONSchema` form to be collapsable, saving precious space 
It extends the custom template used for array items in order to handle the control of the new UI. 
It adds a collapse/expand button on the side toolbar.
The custom handling is configurable through the `UISChema` scheme, with a  'ui:collapsable` attribute added to the `items` property, such as : 
```
subscriptions: {
items: {
'ui:collapsable': {
titleKey: 'destination',
},
},
},
```
The PR also fixes https://hivemq.kanbanize.com/ctrl_board/57/cards/19931/details/

feat(19269): Allow collapsable items in a RJSF form

---

hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DeleteListener.tsx

The PR fixes a bug with the status of the Designer when nodes/edges are deleted, resulting in the toolbar and the "check validity" button to be disabled

fix(19868): Fix disable state of Data Hub check and toolbar

---

hivemq-edge/src/frontend/build.gradle.kts

**Motivation**
I think this file doesn't exists in the project, so it is safe to remove.
**Changes**
- removed .browserslistrc file ref from build.gradle fe script

remove .browserslistrc file ref from build.gradle fe script

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/pnpm-lock.yaml
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DeleteListener.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/ConnectionLine.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/CustomHandle.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/topic_filter/TopicFilterNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18935/details/
The PR fixes a bug with the computation of connecting edges to a handle, allowing correct restrictions on certain connections (e.g. Topic Filter's handles can only have one target)
The PR also fixes the rendering of the icon when dragging a connection from a handle
The PR finally fixes a bug when deleting nodes, whereas connected edges were not automatically deleted and stayed in the data store (not displayed but contributing to the connections count of a node)

fix(18935): Fix the verification of connectivity limits on handles

---

hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/18841/details/
The PR adds component tests for the configuration panel of every one of the Operation nodes supported in Data Hub: 
- `System.log`
- `Delivery.redirectTo`
- `Mqtt.UserProperties.add`
- `Serdes.deserialize`
- `Serdes.serialize`
- `Metrics.Counter.increment`
- `Mqtt.disconnect`
- `Mqtt.drop`
- `DataHub.transform`

test(18841): Add tests for the different operations

---

ext/hivemq-edge-openapi-2024.5.yaml
hivemq-edge/src/frontend/src/api/__generated__/models/ProtocolAdapter.ts
hivemq-edge/src/frontend/src/api/__generated__/models/TypeIdentifier.ts
hivemq-edge/src/frontend/src/api/__generated__/schemas/$TypeIdentifier.ts
hivemq-edge/src/frontend/src/components/rjsf/ArrayFieldTemplate.tsx
hivemq-edge/src/frontend/src/components/rjsf/BatchSubscription/components/DataSourceStep.tsx
hivemq-edge/src/frontend/src/locales/en/components.json
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/types.ts
hivemq-edge/src/main/resources/simulation-adapter-ui-schema.json
modules/hivemq-edge-module-http/src/main/resources/http-adapter-ui-schema.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/22943/details/
The PR fixes a few bugs detected during QA:
- both `HTTP` and `Simulated` adapter have their `uiSchema` fixed for missing  or extra information
- the batch upload button is not available for a newly created adapter, to prevent misconfiguration
- the dropzone now displays the name of the loaded file. File uploading can still be operated. 
The PR also updates the OpenAPI specs to `2024.5` and  the stubs.
- A better Ux for the dropzone is to add a visualisation of the content of the loaded file. It will be part of a subsequent refinement, see https://hivemq.kanbanize.com/ctrl_board/57/cards/23054/details/

fix(22943): Fix bugs with the batch subscription mode

---

hivemq-edge/src/frontend/src/components/rjsf/Widgets/AdapterTagSelect.spec.cy.tsx
hivemq-edge/src/frontend/src/components/rjsf/Widgets/AdapterTagSelect.tsx
hivemq-edge/src/frontend/src/components/rjsf/Widgets/types.ts
hivemq-edge/src/frontend/src/components/rjsf/Widgets/utils/treeview.utils.spec.ts
hivemq-edge/src/frontend/src/components/rjsf/Widgets/utils/treeview.utils.ts
hivemq-edge/src/frontend/src/locales/en/components.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/23330/details/
The PR corrects the logic of the tag browser, only allowing selectable options to be visible in the auto-complete options. 
The `selectable` flag is internal and received from the backend.
The PR also customises the error message when no options are visible, to identify the context (no options available, no selectable options available, no option matching filter)
The PR adds a "breadcrumb" representation of the path of an item in the tree. It could be used for rendering purposes, as an alternative to present a fully, non-accessible treeview
- The application of the `selectable` flag might result in no options available, making the auto-complete component unworkable. An alternative UX, if non-discoverable configuration is …

fix(23330): Only include selectable options in the browser

---

hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/24144/details/
The PR refactors the way the name of a resource (SCRIPT or SCHEMA) is rendered on the node itself. 
Previously, there was an inconsistent mix of internal names and schema's internal properties. 
The current refactoring consistently utilises the `name` and the `version` of the resource, as internally used in the API payload.
- The rendering uses the internal pattern `name:version`
- When a new resource is created, the version will be displayed as `DRAFT`
- When a new version of the resource is created, the version will be rendered as `MODIFIED`

feat(24144): Refactor the name of resources as displayed on their nodes in the Designer

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/pnpm-lock.yaml
hivemq-edge/src/frontend/src/components/Chakra/ContextMenu.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/NodeDatahubToolbar.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/NodeDatahubToolbar.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/NodeWrapper.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/utils/hotkeys.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/hotkeys.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/24140/details/
The PR adds a conditional toolbar to every node on the Designer, containing buttons for the main tasks associated with nodes: edit (open the side panel), copy and delete
- The toolbar is conditional to a node being selected. 
- The toolbar is associated with the node (top)
- If multiple nodes are selected (like for copy), no toolbar is displayed
- The toolbar's size changes based on the zoom factor of the canvas, maintaining a consistent visual
- Multiple selections might benefit from a toolbar, associated with the first node for example, and applying the operation to every node. This might be exploited in a subsequent ticket
- Dispatching the COPY and DELETE hit keys trigger an uncaught error with ReactFlow. This will be …

feat(24140): Add a context toolbar to the nodes on the Designer

---

.github/workflows/frontend-cli.yml
hivemq-edge/src/frontend/cypress.config.ts

To track the flaky component tests

chore(CYPRESS): Enable videos and verbose output

---

hivemq-edge/src/frontend/src/api/hooks/useProtocolAdapters/useGetDataPoints.tsx
hivemq-edge/src/frontend/src/components/rjsf/Widgets/AdapterTagSelect.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/24361/details/
The PR removes a deprecated error throw. The case is dealt with by supporting an alternative field.
- Since the discovery API requires an adapter `id` to work, it cannot be used when creating a new adapter. Without the discovery, there is no possible auto-complete. In such a case, the widget reverts to the default, uncontrolled, input. The issue was raised on the main PR.

fix(24361): Fix bug with deprecated error

---

hivemq-edge/src/frontend/src/modules/ProtocolAdapters/utils/uiSchema.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/24369/details/
The PR turns the custom data point browser off and replace it with the standard text input. It will affect all adapters with the `DISCOVERY` feature and `discovery:tagBrowser` mapping in the `UiSchema`

refactor(24369): Turn discovery browser off

---

hivemq-edge/src/frontend/src/__test-utils__/react-flow/ReactFlowTesting.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/controls/GroupNodesControl.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/controls/GroupNodesControl.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/24988/details/
The PR corrects a misbehaviour when creating groups., by allowing drag-and-select to indicate nodes that need to be grouped. 
The current approach was only considering nodes that were click-and-selected.

fix(24988): Fix the drag-select creation of group

---

hivemq-edge/src/frontend/src/api/hooks/useEvents/__handlers__/index.ts
hivemq-edge/src/frontend/src/modules/App/routes.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/SourceLink.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/SourceLink.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/panel/EventDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/panel/EventDrawer.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolIntegrationStore.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/controls/NodePanelController.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeBridge.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/25468/details/
The PR is a quick fix to change the router for adapters
- The routes are now including the `type` of the adapter
- The children's routes are rewritten to avoid conflicts

refactor(25468): Refactor adapter routes to expose the adapter type

---

ext/hivemq-edge-openapi-2024.7.yaml
hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/src/api/__generated__/HiveMqClient.ts
hivemq-edge/src/frontend/src/api/__generated__/core/OpenAPI.ts
hivemq-edge/src/frontend/src/api/__generated__/index.ts
hivemq-edge/src/frontend/src/api/__generated__/models/Bridge.ts
hivemq-edge/src/frontend/src/api/__generated__/models/WebsocketConfiguration.ts
hivemq-edge/src/frontend/src/api/__generated__/schemas/$Bridge.ts
hivemq-edge/src/frontend/src/api/__generated__/schemas/$WebsocketConfiguration.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/BridgeMainDrawer.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/WebSocketPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/WebSocketPanel.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/24592/details/
The PR adds a new tab to the `Bridge` configuration panel, allowing users to enable websockets and their options
- Both `serverpath` and `subprotocol` are open string input, without any validation
- There are now 5 tabs in the configuration panel, reaching a good-practice limit. Reorganising the options should be part of a subsequent ticket

feat(24592): Add the websocket configuration to the UI

---

hivemq-edge/src/main/resources/simulation-adapter-ui-schema.json
modules/hivemq-edge-module-http/src/main/resources/http-adapter-ui-schema.json
modules/hivemq-edge-module-modbus/src/main/resources/modbus-adapter-ui-schema.json
modules/hivemq-edge-module-opcua/src/main/resources/opcua-adapter-ui-schema.json
modules/hivemq-edge-module-plc4x/src/main/resources/s7-adapter-ui-schema.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/25622/details/
The PR prevents a significant bug with the compact table widget, removing the mapping from the existing adapters. 
- the code for te RJSF widgets and templates is still in the frontend. It will be refactored to remove the unexpected side effect in a further ticket.

fix(25622): remove compact table from adapter's UISchema

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/ContextualToolbar.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeDevice.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeDevice.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/26909/details/
This PR is part of the bi-directional epic and fixes a consistency issue with node toolbars on the workspace. 
The Device toolbar, to manage tags, is now on the left-hand side, consistent with the mapping toolbar for the adapter nodes 
- The device node remains underspecified (no information about devices in the system)
- The "overview" CTA on the right-hand side is non-existent. It also means the device node doesn't react to double-click or right-click like the other node. There is no visual feedback to support differences between the two states. This will be dealt with in a subsequent ticket.

refactor(26909): Refactor device toolbar

---

hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/26934/details/

move status check of the adapters to enable cleanup of data policies that were created by not yet started adapters

---

hivemq-edge/src/frontend/src/api/hooks/useProtocolAdapters/__handlers__/index.ts
hivemq-edge/src/frontend/src/api/types/json-schema.ts
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useMappingManager.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/Workspace/utils/status-utils.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/topics-utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/27781/details/
The PR fixes a bug with the extraction of mapping schemas from the main config schema, whereas potential definitions were not extracted. The fix takes care of both `definitions` and `$defs` syntax for the JSONSchema element.
The PR also fixed two small issues:
- the visual rendering of status on the links to devices in the workspace has been corrected to reflect the creation of outward mappings.
- the topics used for outward mappings are now displayed on the top-side of the adapter node, replicating the pattern introduced with inward mappings. 
It is worth noting that the display is a temporary placeholder, using a "tag" rendering while in fact it shows the source topic filter. This is to create an expected placeholder, …

fix(27781): Fix extraction of mapping schema

---

hivemq-edge/src/frontend/src/__test-utils__/react-flow/nodes.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/Workspace/hooks/useWorkspaceStore.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/hooks/useWorkspaceStore.ts
hivemq-edge/src/frontend/src/modules/Workspace/types.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/nodes-utils.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/nodes-utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/27867/details/
A simple fix to enable the `workspace` to show the `device` node of every `adapter` created. 
Initially, `devices` were only added for adapters supporting bi-directionality. 
However, the generalisation of `tags` for mapping, regardless of direction, enabled the co-location of the `tags` within the `device` namespace, and the necessity of their presence on the `workspace`.
The PR also fixes a bug with the `device` node not being deleted when their `adapter` is.
- Content of the `device` nodes is still not accurate but will be delivered in subsequent tickets

fix(27867): add device node to every adapter in the workspace

---

ext/hivemq-edge-openapi-2024.8-SNAPSHOT.yaml
hivemq-edge/src/main/java/com/hivemq/api/adapters/AdapterConfigModel.java
hivemq-edge/src/main/java/com/hivemq/api/resources/ProtocolAdaptersApi.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/config/EipAdapterConfig.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/FilePollingProtocolAdapter.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/config/FileAdapterConfig.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/config/FileToMqttConfig.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/ModbusAdapterConfig.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaClientWrapper.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/OpcUaAdapterConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/config/Plc4xAdapterConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/config/ADSAdapterConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/config/S7AdapterConfig.java

**Motivation**
Resolves #27907
**Changes**
When introducing the new userflow (first creating the config, then the tags + mappings) the changes didn't reflect through to all config objects.
Several places had NotNull-annotations and others relied on the values not being null.

Fixing issues with the new userflow where a missing mqttTo-config causes NPEs

---

hivemq-edge/src/frontend/src/components/rjsf/ArrayFieldItemTemplate.tsx
hivemq-edge/src/frontend/src/components/rjsf/Form/ChakraRJSForm.tsx
hivemq-edge/src/frontend/src/components/rjsf/Form/error-focus.utils.spec.ts
hivemq-edge/src/frontend/src/components/rjsf/Form/error-focus.utils.ts
hivemq-edge/src/frontend/src/components/rjsf/Form/types.ts
hivemq-edge/src/frontend/src/components/rjsf/Form/useFormControlStore.spec.ts
hivemq-edge/src/frontend/src/components/rjsf/Form/useFormControlStore.ts
hivemq-edge/src/frontend/src/components/rjsf/ObjectFieldTemplate.tsx
hivemq-edge/src/frontend/src/components/rjsf/Templates/ErrorListTemplate.tsx
hivemq-edge/src/frontend/src/locales/en/components.json
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/26339/details/
The PR significantly improves the rendering of the error summary in all the RJSF-based forms. The main problem was error messages mentioning an input field that might be on a grouping tab not currently active or within a "collapsed" item in an array. In such situations, not only would the field with the property not be visible to the users, but its location would not even be mentioned.  
- The warning in the browser for trying to focus on a hidden DOM element has been removed by disabling HTML5 validation that was already creating conflict with the form-based validation
- The error list has been redesigned to include two elements on each item
- If an error is in a tab, the name of the tab is displayed before the error …

feat(26339): Improve errors display in RJSF forms and handle focus on hidden widget

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java

**Motivation**
Resolves #<28589>
**Changes**
The call to retrieve  the list of fomain-tags for an existing adapter which doesn't have configured tags now returns an empty object instead of null.

Retrieving empty lists of domaintags gave a null body instead of an empty list

---

hivemq-edge/src/frontend/src/api/schemas/northbound.ui-schema.ts
hivemq-edge/src/frontend/src/components/rjsf/Fields/MqttTransformationField.tsx
hivemq-edge/src/frontend/src/components/rjsf/Form/ChakraRJSForm.tsx
hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/components/MappingContainer.tsx
hivemq-edge/src/frontend/src/components/rjsf/SplitArrayEditor/components/ArrayItemDrawer.tsx
hivemq-edge/src/frontend/src/components/rjsf/Widgets/EntitySelectWidget.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationPanel.spec.cy.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Device/components/DeviceTagForm.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Device/components/DeviceTagForm.tsx
hivemq-edge/src/frontend/src/modules/Device/components/DeviceTagList.tsx
hivemq-edge/src/frontend/src/modules/Device/hooks/useTagManager.spec.tsx
hivemq-edge/src/frontend/src/modules/Device/hooks/useTagManager.ts
hivemq-edge/src/frontend/src/modules/Device/utils/validation.utils.spec.ts
hivemq-edge/src/frontend/src/modules/Device/utils/validation.utils.ts
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useNorthboundMappingManager.spec.tsx
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useNorthboundMappingManager.ts
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useSouthboundMappingManager.spec.tsx
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useSouthboundMappingManager.ts
hivemq-edge/src/frontend/src/modules/Mappings/types.ts
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/utils/validation-utils.spec.ts
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/utils/validation-utils.ts
hivemq-edge/src/frontend/src/modules/TopicFilters/TopicFilterManager.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/TopicFilterManager.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/hooks/useTopicFilterManager.spec.ts
hivemq-edge/src/frontend/src/modules/TopicFilters/hooks/useTopicFilterManager.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/27975/details/
This PR adds client-side validation for device tags, ensuring they are unique per device but also across the Edge instance. 
The PR also re-introduces other validations that wehnt missing due to the refactoring
- tag, topic and topic filter names are validated on input
- tag and topic filter references are through a select widget only (with options provided from list of candidates, no creation allowed)
- topic references is provided through the select widget that allows creation

feat(27975): tag uniqueness and other validation updates

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/IntegrationStore/ProtocolsBrowser.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/IntegrationStore/ProtocolsBrowser.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/26143/details/
The PR adds a link to installation instructions when an adapter is not installed locally.
- installation is determined by the `installed` property of the adapter
- the link is the same as the documentation (from the `url` property)

feat(26143): add installation instructions

---

hivemq-edge/src/frontend/src/api/hooks/useTopicFilters/__handlers__/index.ts
hivemq-edge/src/frontend/src/api/hooks/useTopicFilters/useListTopicFilters.spec.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/TopicFilters/TopicFilterManager.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/TopicFilterManager.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/SchemaSampler.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/SchemaSampler.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/SchemaUploader.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/SchemaUploader.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/SchemaValidationMark.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/SchemaValidationMark.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/TopicSchemaDrawer.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/TopicSchemaManager.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/hooks/useTopicFilterManager.spec.ts
hivemq-edge/src/frontend/src/modules/TopicFilters/hooks/useTopicFilterManager.ts
hivemq-edge/src/frontend/src/modules/TopicFilters/utils/topic-filter.schema.spec.ts
hivemq-edge/src/frontend/src/modules/TopicFilters/utils/topic-filter.schema.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/28664/details/
This PR creates a new UX for managing the schema associated with topic filters. It refactors the secondary editor flow in the main list of topic filters (accessible through the  "manage schema" CTA on every item).
The flow is based on three distinct operations:
- the "current schema", if already present, is displayed using the generic rendering paradigm. It is possible to remove it.
- a schema can be "uploaded" using a drag-and-drop interface or a file selector. The file is expected to be a JSON document, valid with JSON-Schema specification 
- a schema can be "inferred" from the traffic on the current Edge instance. If matching topics exist, all their schemas are displayed, for one of them to be selected for replacing …

feat(28664): Add schema management for the topic filters

---

modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/payload/FileJsonPayloadCreator.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/payload/FilePayload.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/27400/details/

make file adapter respect flags

---

hivemq-edge/src/frontend/src/locales/en/translation.json

https://hivemq.kanbanize.com/ctrl_board/57/cards/28152/details/

fix(28152): fix translations

---

modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/util/AdapterDataUtils.java
modules/hivemq-edge-module-modbus/src/test/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterTest.java

**Motivation**
Resolves #28848
**Changes**
ModbusAdapter was casting the incoming PolingContext to the wrong type.
Since this was only used for delta-calculations it broke only those.

Modbus was internall casting a PollingContext to the wrong object when trying to determine deltas, breaking delta sending

---

hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/Workspace/utils/status-utils.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/status-utils.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/topics-utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/28866/details/
The PR updates the old "topic tag" in the adapter node with the new mapping paradigm. 
- They cannot be called "tags" anymore since we now have "Device Tags" in the mapping
- As they are basically labels to the link handles on a node, they could be termed "configuration labels"
-  Northbound mappings provides the topics for the labels to the connection with the Edge node
- Southbound mappings provides the topics filters for the labels to the connection with the Device node
The PR also fixes the connection status of an adapter, as rendered by the colour of the links between the nodes. Bi-directionality is rendered by an arrowed link to the Device node, by contract to a plain link when uni-directional,

fix(28866): Fix the configuration flags of the adapter nodes

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdapterApiUtils.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
hivemq-edge/src/test/java/com/hivemq/protocols/ProtocolAdapterManagerTest.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/EipProtocolAdapterInformation.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/FileProtocolAdapterInformation.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterInformation.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterInformation.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/28919/details/

Polishing for release

---

hivemq-edge/src/frontend/src/components/react-flow/ToolbarButtonGroup.spec.cy.tsx
hivemq-edge/src/frontend/src/components/react-flow/ToolbarButtonGroup.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/ContextualToolbar.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeBridge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeDevice.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeDevice.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeEdge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeGroup.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeGroup.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/27875/details/
The PR replaces the unconvincing side CTAs with a common toolbar with a more consistent content. The toolbar is also used to display the name of the node, which can prove helpful when used in a small zoom factor.

feat(27875): Redesign the workspace toolbars

---

hivemq-edge/src/frontend/src/components/rjsf/ArrayFieldItemTemplate.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/28701/details/
The PR fixes a major usability issue, by styling array items with the common "red" border when a validation error is generated but the item is "folded" and doesn't materialise the error

fix(28701): fix style of folder array items when error

---

hivemq-edge/src/frontend/src/components/ExpandableDrawer/ExpandableDrawer.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/AdapterMappingManager.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/TopicFilterManager.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/TopicFilterManager.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/DevicePropertyDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/DevicePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/EdgePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/LinkPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/NodePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/NodeNameCard.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/NodeNameCard.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/28703/details/
The PR fixes a significant usability issue, whereas most of the side panels opening in the workspace would not mention which node or link would have triggered the opening.
The side panels now contain a cartouche in the header which will indicate which content is associated with the specific instance of the panel. 
The content of that cartouche has been normalised to render the icon of the entity, its name and its description. 
Note that, in most cases, the trigger of the side panel will be one of the nodes on the workspace (or a link connecting them). The cartouche therefore refers to these nodes, which might reinforce a somehow loose coupling (e.g. `topic filters` being located within the `Edge` node)

refactor(28703): Add the source of a side panel into its header

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/mqtt2opcua/BuiltinJsonSchema.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/mqtt2opcua/JsonSchemaGenerator.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/mqtt2opcua/JsonToOpcUAConverter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/opcua2mqtt/OpcUaJsonPayloadConverter.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/mqtt2opcua/JsonToOpcUAConverterTest.java

**Motivation**
Resolves #28937
**Changes**
OPCUA was not able to use arrays for Southbound.

Added support for arrays

---

hivemq-edge/src/frontend/src/api/schemas/northbound.ui-schema.ts
hivemq-edge/src/frontend/src/components/rjsf/ArrayFieldItemTemplate.tsx
hivemq-edge/src/frontend/src/components/rjsf/utils/array-items.utils.spec.ts
hivemq-edge/src/frontend/src/components/rjsf/utils/array-items.utils.ts
hivemq-edge/src/frontend/src/locales/en/components.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/28713/details/
The PR change the pattern of the default name for items in a `RJSF` form. 
- the pattern in used is more readable: `name #1 - content`
- the default name is `item`
- if a `ui:title` is given, then it replaces the name
Note that the fix involves overriding a name that is hardcoded by the `RJSF` library. It might not be resilient to code updates.

fix(28713): change generated name for array items

---

hivemq-edge/src/frontend/src/__test-utils__/mocks.ts
hivemq-edge/src/frontend/src/api/hooks/useGetMetrics/__handlers__/index.ts
hivemq-edge/src/frontend/src/modules/Metrics/MetricsContainer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/MetricsContainer.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/editor/MetricEditor.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/components/editor/MetricEditor.tsx
hivemq-edge/src/frontend/src/modules/Metrics/types.ts
hivemq-edge/src/frontend/src/modules/Metrics/utils/metrics-name.utils.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/LinkPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/NodePropertyDrawer.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/28895/details/
The PR fixes a bug in the rendering of the list of metrics available for groups. The process was considering device nodes in the list of available targets for metrics, resulting in a wrong list 
Device nodes are now properly excluded from the processing of metrics

fix(28895): Fix rendering of metrics for groups

---

hivemq-edge/src/frontend/src/api/hooks/useProtocolAdapters/__handlers__/index.ts
hivemq-edge/src/frontend/src/modules/Device/components/DeviceMetadataViewer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Device/components/DeviceMetadataViewer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeDevice.tsx
hivemq-edge/src/frontend/src/modules/Workspace/types.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/nodes-utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/28933/details/
The PR fixes a glaring gap. Device tags are now rendered on the device node, similar to how topic filters and topics are shown on the adapters.
The PR also improves the layout of the device node
- The "glued" relation between a device and its adapter adapter is rendered by a fixed distance between the two nodes, from top to top. The distance reflects the gap needed to render two tags in the device node. The layout should be more dynamic, by having a constant length of the link between the two nodes, i.e. from bottom to top. This will be done in a subsequent ticket

fix(28933): Add device tags to the node visualisation

---

hivemq-edge/src/frontend/src/components/Icons/TopicIcon.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/adapters/AdapterActionMenu.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/adapters/AdapterActionMenu.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/types.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/controls/SelectionListener.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29159/details/
The PR is the first step in resolving the lack of context for managing tsgs, topic filters and mappings in the workspace after creating a new adapter in a different context of the application 
In the adapter list, the PR adds several items in the contextual menu ("actions£) of an adapter, under the common group "Manage from Workspace": 
- Device Tags
- Topic Filters
- Northbound mappings
- Southbound mapping (if enabled for the adapter)
- Adapter and Device
Each of the commands links to the relevant node on the workspace. The transition is animated, with a managed zoom ("fit view") on the relevant node(s). 
The animation and zoom should help to contextualise the different elements of an adapter that requires further …

feat(29159): Improve the integration of the adapter page with the workspace

---

hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.spec.cy.tsx
hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/adapters/AdapterStatusContainer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/adapters/AdapterStatusContainer.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx
hivemq-edge/src/frontend/src/modules/Theme/foundations/colors.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/NodePropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/GroupContentEditor.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/GroupContentEditor.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/GroupMetadataEditor.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/GroupMetadataEditor.tsx
hivemq-edge/src/frontend/src/modules/Workspace/utils/adapter.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/28974/details/
The PR refactors the content of the side panel associated with custom groups on the workspace, making it consistent with the other nodes. 
- the layout of the panel is now split into three tabs: configuration, events and metrics
- the header of the group panel is now consistent with all the other side panels
- the configuration of the group (title and colour) is complemented by the list of all nodes in the group
- the event tab shows the most recent events for all nodes in the group. A link allows access to the complete event log
- the metrics tab contains the observability dashboard for all nodes in the group
- the actions in the list of nodes are disabled since we lack an easy way of controlling several adapters at a …

feat(28974): Refactor the group side panel in the workspace

---

hivemq-edge/src/frontend/src/components/PageContainer.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/App/routes.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/ProtocolAdapterPage.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/ProtocolAdapterPage.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolIntegrationStore.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolIntegrationStore.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29205/details/
The PR refactors the adapter landing page in order to simplify the navigation to, from and between active adapters and the protocol catalogue
- The `Active Adapters` and `Protocol Adapter Catalog` tabs have been removed from the old landing page
- The new landing page is consistently showing the list of `Active Adapters`
- whether you are a new user or not
- whether the list is empty or not
- The landing page has a primary CTA in its banner (consistent with the Bridge landing page) labelled `Add a new Adapter`  
- The CTA leads to the `Protocol Adapter Catalog` page (replacing the `Active Adapters` list); a new secondary CTA, labelled `Back to active adapters` allows users to navigate back to the landing page
- Creating a …

refactor(29205): Improve the UX flow on the adapter pages

---

hivemq-edge/src/frontend/src/components/Chakra/ShortcutRenderer.spec.cy.tsx
hivemq-edge/src/frontend/src/components/Chakra/ShortcutRenderer.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DesignerCheatSheet.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DesignerCheatSheet.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/locales/en/components.json
hivemq-edge/src/frontend/src/utils/user-agent.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/27115/details/
The PR fixes a few issues with the shortcut cheatsheet in the Designer:
- detection of the user agent (platform) made more resilient 
- shortcuts are displayed using the reduced version of the modifier (`⌘` instead of `Command`)
- The `Designer` is a "normal" widget displayed in the DOM, like any other interactive element: it reacts to `tab` navigation and other keyboard rules of HTML 
- The `Designer` is not a modal, therefore it doesn't "trap" the `tabs` within its confine: tab iteration will go through the internal elements of the `Designer` (links, nodes, UI elements) before continuing back to the rest of the page (e.g. side navigation)

fix(27115): Fix bugs with the Designer shortcuts

---

hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DeleteListener.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DeleteListener.tsx

See 
A quick fix for preventing an unnecessary confirmation message when there are no element to delete

fix(29347): fix bug with empty targets of deletion

---

hivemq-edge/src/frontend/src/components/PageContainer.spec.cy.tsx
hivemq-edge/src/frontend/src/components/PageContainer.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CopyPasteStatus.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/CopyPasteStatus.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DesignerToolbox.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DesignerToolbox.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolGroup.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolGroup.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolItem.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolItem.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxNodes.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DraftStatus.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/ConnectionLine.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
hivemq-edge/src/frontend/src/extensions/datahub/hooks/useDataHubDraftStore.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/hooks/useDataHubDraftStore.ts
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/extensions/datahub/types.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Workspace/components/ReactFlowWrapper.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/27113/details/
The PR refactors the designer's UX so that a single police node (either `Data Policy` or `Behavior Policy`) can be present in the canvas at a given time. 
The restriction applies to the loading of policies and to the creation of a new `draft`: the toolbox is disabled when one of the two nodes is added, and the contextual connection (when a node is created by dragging a handle) cannot create a new node on drop.
The PR also redesigns the toolbox to improve usability and accessibility, and also to make it more future-friendly (e.g. adding new construction inodes)
- Several aspects of the Designer will be refactored in a subsequent ticket, to reflect comments and suggestions made on this epic

refactor(27113): Ensure a single policy used in the Designer

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/HiveMQConfigEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/ProtocolAdapterEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/migration/ConfigurationMigrator.java
hivemq-edge/src/main/java/com/hivemq/configuration/migration/LegacyHiveMQConfigEntity.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterConfig.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterConfigConverter.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
hivemq-edge/src/main/resources/config.xsd
hivemq-edge/src/test/java/com/hivemq/protocols/ProtocolAdapterManagerTest.java
hivemq-edge/src/test/resources/test-config.xml
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/EipProtocolAdapterInformation.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/FileProtocolAdapterInformation.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterInformation.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterInformation.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/27422/details/
Currently we have no way to find out for what edge version a given config.xml was written. This makes it hard to find out which migrations might be needed. A simple version field that indicates that will resolve this issue.

Add version to config

---

hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
hivemq-edge/src/frontend/src/extensions/datahub/designer/checks.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/client_filter/ClientFilterNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/topic_filter/TopicFilterNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29589/details/
See https://hivemq.kanbanize.com/ctrl_board/57/cards/29579/details/
The PR fixes the computation of the initial position of the nodes on the canvas when a policy is loaded. It changes the basis of the layout to match the new design constraints (left-to-right orientation of policy graphs)
The positions are not persisted with the policy so the loaded policy needs to be re-layouted at load time. The process in place is a simple predecessor- and grid-based position shifting, not a full graph layout: overlaps are still expected. 
The PR also fixes an irritating anti-pattern: when constructing a node by dragging from the handle, the new node is created based on the expected position of the new handle, guaranteeing alignment.

refactor(29589): Refactor the nodes' initial position in the Designer

---

hivemq-edge/src/main/java/com/hivemq/persistence/domain/DomainTag.java

**Changes**
When encountering a null for description it is now replaced with an empty string.

FIxed a bug where null-values resulted in nonrenderable json

---

hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DraftStatus.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/toolbar/NodeDatahubToolbar.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/toolbar/ToolbarPublish.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/toolbar/ToolbarPublish.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/modules/Theme/globals/react-flow.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29524/details/
This PR fixes the publishing process of a policy by allowing users to modify a published policy.
In the previous releases, policies could only be created once, as the "modify" part of the process had never been implemented. 
The constraints on policies, both `Data` and `Behaviour` remain the same
- the policy node itself cannot be modified (in practice, its 'id`)
- the triggers (topic filter and client filter) cannot be modified
- Modifying an existing resource creates a new one (new version)
- Multiple resources are not properly published, see https://hivemq.kanbanize.com/ctrl_board/57/cards/29734/details/
- Persistence of the policy layout is not yet supported, see …

feat(29524): Enable modification of published policy

---

hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.spec.ts
hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29608/details/
The PR fixes the display of the resource's version in the Designer. The version number will be shown, `DRAFT` for a new resource and `MODIFIED` for a new version of an existing resource. The fix applies to both `Schema` and `Function`.
For compatibility purposes, the non-published version of a resource is internally identified by a number (9 ** 9 for DRAFT, incremented for MODIFIED). These fake numbers are unlikely to be reached by the `Data Hub`c version increment. But they should not be displayed as such 
- There is a bug loading a new version, where `latest` is not found (nor the list of the different versions). It will be fixed in another ticket.

fix(29608): Fix the display of resource version

---

hivemq-edge/src/main/java/com/hivemq/HiveMQEdgeBootstrap.java
hivemq-edge/src/main/java/com/hivemq/api/errors/ConfigWritingDisabled.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/BridgeResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/TopicFilterResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/UnsResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/configuration/EnvironmentVariables.java
hivemq-edge/src/main/java/com/hivemq/configuration/SystemProperties.java
hivemq-edge/src/main/java/com/hivemq/configuration/info/SystemInformation.java
hivemq-edge/src/main/java/com/hivemq/configuration/info/SystemInformationImpl.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImplTest.java

**Motivation**
Resolves #29317
**Changes**
- Add config-writeable
- Enable capability via property hivemq.config.writeable or env HIVEMQ_CONFIG_WRITEABLE (enabled if both are absent
- Have all writing endpoints return a 403 with ConfigWritingDisabled as the body when writing id disabled

Add a capability to indicate whether config can be written back. Adjust endpoints accordingly

---

hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DesignerToolbox.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DraftStatus.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/toolbar/ToolbarShowReport.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/toolbar/ToolbarShowReport.tsx
hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29845/details/
The PR fixes several small UI glitches on the `Data Hub Designer`
- The label for the "canvas draft" has been changed, to highlight the difference with the bona fide policies in the table
- The publish toolbar has full-text button for all operations: `check`, `show report` and `publish`
- A margin has been added to the top-left toolbar

fix(29845): A handful of UI improvements

---

hivemq-edge/src/frontend/src/api/hooks/useFrontendServices/__handlers__/index.ts
hivemq-edge/src/frontend/src/api/hooks/useFrontendServices/useGetCapability.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Notifications/hooks/useGetManagedNotifications.spec.ts
hivemq-edge/src/frontend/src/modules/Notifications/hooks/useGetManagedNotifications.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29319/details/
The PR adds a notification when the `config-writeable` capability is NOT defined
- Capabilities MUST be curated in the OpenAPI specs, not replicated on the front end. This will be part of a further ticket
- The intended usage of the capability has been inverted. The critical aspect worth notifying users about is when the config is NOT writable, triggering error messages (403) at the front end. However, that state is (mis)detected by the capability (config is writable) being not present in the capabilities list. The `undefined` content could mean not supported but also not found or API to get the capabilities failed. As the logician says: "Absence of Evidence does not mean Evidence of Absence”. This will be fixed in a …

feat(29319): Add notification of not writable config

---

build.gradle.kts
docker/config-k8s.xml

**Motivation**
Resolves #30295
For pod securityContexts we must allow the container to work with differing users being used than the one defined in the container.
**Changes**
- Allow others (as in ugo) to run the shell scripts, access all required directories and write to hivemq home

Changed access rights for dirs and scripts so they can be used with changing user ids

---

hivemq-edge/src/main/java/com/hivemq/http/JaxrsHttpServer.java
hivemq-edge/src/test/java/com/hivemq/embedded/internal/EmbeddedHiveMQImplHttpTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/30439/details/
**Motivation**
This is to allow Edge to be accessible behind an Ingress that does TLS-termination we generate a redirect to an http-URL.
**Changes**
* Add server property `jersey.config.server.headers.location.relative.resolution.disabled` to jersey
* Add unit test case to verify `/` is redirected to `/app/`

fix(30439): Enable relative path for redirection

---

hivemq-edge/src/frontend/src/api/hooks/useDomainModel/useGetCombinedDataSchemas.spec.ts
hivemq-edge/src/frontend/src/api/hooks/useDomainModel/useGetCombinedDataSchemas.ts
hivemq-edge/src/frontend/src/api/hooks/useDomainModel/useGetCombinedEntities.spec.ts
hivemq-edge/src/frontend/src/modules/Mappings/CombinerMappingManager.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedEntitySelect.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedEntitySelect.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedSchemaLoader.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedSchemaLoader.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/DataCombiningEditorField.tsx
hivemq-edge/src/frontend/src/modules/Mappings/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30678/details/
The PR is the next step in building the UX for the data-combining feature of Edge, see https://hivemq.kanbanize.com/ctrl_board/57/cards/29097/details/. It implements the fetching and handling of the schema associated with the aggregated `tags` and `topic filters`. 
- Upon selection of a tag or a topic filter in the combined widget, schemas are fetched and processed for rendering
- Schemas (or their error messages) are displayed in the form in the order the tags or topic filters have been selected. They will both show the name of the data identifier/.
- If a schema is valid (i.e. a JSONSchema delivered either as a JSON object or as a `data-uri` encoded string), it is rendered as a list of draggable properties 
- If the …

feat(30678): Add support for schema fetching on the sources

---

hivemq-edge/src/frontend/src/api/__generated__/models/DataCombining.ts
hivemq-edge/src/frontend/src/api/__generated__/schemas/$DataCombining.ts
hivemq-edge/src/frontend/src/api/hooks/useCombiners/__handlers__/index.ts
hivemq-edge/src/frontend/src/api/hooks/useCombiners/useListCombinerMappings.spec.ts
hivemq-edge/src/frontend/src/api/hooks/useCombiners/useListCombiners.spec.ts
hivemq-edge/src/frontend/src/api/schemas/combiner-mapping.json-schema.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/DataCombiningEditorField.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/DataCombiningTableField.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/DestinationSchemaLoader.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/DestinationSchemaLoader.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30678/details/
The PR is the next step in building the UX for the data-combining feature of Edge, see https://hivemq.kanbanize.com/ctrl_board/57/cards/29097/details/. It implements the handling of the destination schema
-  Adding a schema is contingent on a destination topic being selected 
- The "upload schema" CTA opens a dropdown with the now-ubiquitous user interface for uploading files (drag-and-drop or select)
- Note that the file upload is based on the file extension (`.json`) but not on the content of the file
- Upload uploading the schema will be rendered using the same property-based display used in the source schemas.
- The "download schema" is available to save a copy of the schema into a timestamped `.json` document 
- The …

feat(30680): Add support for destination schema

---

hivemq-edge/src/frontend/src/api/hooks/useCombiners/index.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/CombinerMappingManager.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Mappings/CombinerMappingManager.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/DangerZone.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/DangerZone.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30602/details/
The PR adds a small but important aspect of the combiner user flow: the ability to delete a combiner after its creation. 
- A "delete" button, clearly labelled as "danger", has been added to the foot of the main panel associated with a combiner
- The operation needs validation in the modal
- The operation cannot be reversed
- The `DELETE /combiner` request might fail for internal reasons. In such case, the deletion will not have been applied
- The "delete" CTA could also be made available in the toolbar, pending usability testing. This will be part of the refactoring of the `Workspace`, https://hivemq.kanbanize.com/ctrl_board/57/cards/30497/details/

feat(30602): Support deleting combiners

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/CombinerMappingManager.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedEntitySelect.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedSchemaLoader.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/EntityRenderer.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30890/details/
The PR fixes a bug which prevented the `topic filter` from being available to the mappings.
If no `bridge` was added to the selected entities in the workspace, then `topic filters` would not be processed. This situation is not corrected by ensuring that the `Edge` entity, as the owner of the `topic filters` is automatically added to the list of sources
The PR also improves error message on the schema selector and remove duplicates from the list of tag/topic filters.
- Sources, including the `edge` cannot be removed from the `combiner`. When that is the case, a decision on keeping the `edge` node as a default source must be taken
- Error message has been improved (mentioning the right type of source) but is still lacking …

fix(30890): Ensure that topic filters are in the mapping selector

---

hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/components/MappingEditor.spec.cy.tsx
hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/components/MappingInstructionList.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30892/details/
Fix a bug with the "flattening" of properties that prevented nested properties from being displayed in the drag-and-drop editor
Notes
- The reason for the original filter has been lost ! 
- The fix will also impact the southbound mapping editor

fix(30892): remove the filter on "supported" properties

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedEntitySelect.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30712/details/
The PR adds a custom renderer to improve the identification of the tags and topic filters in the options of the selector.

feat(30712): add custom renderer for the options of the entity selector

---

hivemq-edge/src/frontend/src/components/rjsf/Form/ChakraRJSForm.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/CombinerMappingManager.tsx
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useValidateCombiner.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30829/details/
The PR adds custom validation to the `combiner` payload, augmenting the basic elements of the OpenAPI specs. 
The custom validations are rules expressed with the `RJSF` framework, which means they integrate (almost) completely with the UX in the form:  
- errors are associated with specific properties of the schema
- when triggered, the message is displayed by the relevant widget in the form UI (or will be)
- errors are also listed in the summary at the bottom of the form
- The following validation rules are in operation: 
```json
{
"notValidReference": "This is not a valid reference to a Workspace entity",
"notCombineCapability": "The adapter does not support data combining and cannot be used as a source", …
```

feat(30829): Add custom validation to the combiner form

---

hivemq-edge/src/frontend/src/components/PaginatedTable/components/PaginationBar.spec.cy.tsx
hivemq-edge/src/frontend/src/components/PaginatedTable/components/PaginationBar.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30988/details/
The PR is a quick fix to hide the page indicators when there is no page available (i.e. no data to render). This only concerns the data-related controls; the "items per page" is still active.
The PR also adds missing tests
Note that the fix will apply to EVERY table used in Edge

fix(30988): Fix the pagination bar when no page exists

---

hivemq-edge/src/frontend/src/hooks/useEdgeToast/toast-utils.ts
hivemq-edge/src/frontend/src/modules/Mappings/CombinerMappingManager.tsx
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useNorthboundMappingManager.ts
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useSouthboundMappingManager.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30954/details/
The PR fixes a configuration bug resulting in `Combiner` toasts not being closable by end users.

fix(30954): Ensure combiner toasts can be manually closed

---

hivemq-edge/src/frontend/src/components/MQTT/EntityTag.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/DataCombiningTableField.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/PrimarySelect.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30987/details/
The PR adds visual cues to the data point, `tag` or `topic filter`, that is used as a `primary key` for the listed mapping. Only one of the presented data points must have the primary cues.
In this first iteration, cues are a `key` icon in a tag wrapping the data tag. The `key` icon has also been added to the selector in the main editor, for contextualization 
The PR also fixes an accessibility issue (label of the table)

fix(30987): Add styling for the primary key in the tabular summary

---

hivemq-edge/src/frontend/src/api/schemas/combiner-mapping.ui-schema.ts
hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/JsonSchemaBrowser.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/DomainOntology/components/MetadataExplorer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedEntitySelect.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/CombinedSchemaLoader.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/DataCombiningEditorField.tsx
hivemq-edge/src/frontend/src/modules/Mappings/components/combiner/DestinationSchemaLoader.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/SchemaSampler.spec.cy.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30982/details/
The PR adds a form control to every widget in the combiner mapping editor, in effect adding proper title, helper and error messages to them.
The PR also improves on the main layout of the editor
- Validation and error messages for schema is missing. Will be added at a later stage, see https://hivemq.kanbanize.com/ctrl_board/57/cards/31362/details/ and https://hivemq.kanbanize.com/ctrl_board/57/cards/31360/details/
- The southbound editor, using the same mapping UX, needs updating. See https://hivemq.kanbanize.com/ctrl_board/57/cards/31363/details/

fix(30982): Add Form Control to all widgets in the mapping editor

---

hivemq-edge/src/frontend/src/components/rjsf/BatchModeMappings/components/DataSourceStep.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/toolbar/ToolbarPublish.tsx
hivemq-edge/src/frontend/src/hooks/useEdgeToast/toast-utils.ts
hivemq-edge/src/frontend/src/hooks/useEdgeToast/useEdgeToast.tsx
hivemq-edge/src/frontend/src/modules/Device/hooks/useTagManager.ts
hivemq-edge/src/frontend/src/modules/Notifications/NotificationBadge.tsx
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/ExportDrawer.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/components/SchemaUploader.tsx
hivemq-edge/src/frontend/src/modules/TopicFilters/hooks/useTopicFilterManager.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/ContextualToolbar.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30993/details/
The PR fixes the `Designer` publish toasts, preventing duplicates to be shown when repeatedly pressing "publish".
The PR also ensures that every toasts in Edge are using the same base config.

fix(30993): Improving toast management

---

hivemq-edge/src/frontend/src/components/Icons/index.ts
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DryRunPanelController.tsx
hivemq-edge/src/frontend/src/extensions/datahub/utils/datahub.utils.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Theme/utils.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/ContextualToolbar.tsx
hivemq-edge/src/frontend/src/modules/Workspace/utils/combiner.utils.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/combiner.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30741/details/
The PR adds checks to the creation of a new combiner:
- Every selected adapter source must have the `COMBINE` capability. If not, the combiner will be created by excluding those without. 
- If a combiner using the same set of sources already exists, creating a new one will be prevented. The user will be redirected to the combiner's configuration panel, and adding mappings to this one will be suggested.

fix(30741): Add checks for valid combiner creation

---

hivemq-edge/src/frontend/src/api/schemas/combiner-mapping.json-schema.ts
hivemq-edge/src/frontend/src/components/MQTT/EntityTag.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/controls/DryRunPanelController.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeBridge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeCombiner.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeCombiner.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeDevice.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeEdge.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeEdge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/MappingBadge.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/MappingBadge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/parts/NodeNameCard.tsx
hivemq-edge/src/frontend/src/modules/Workspace/utils/adapter.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30538/details/
The PR improves the visual identity of the `combiner` node in the `workspace`, in particular by adding the `topic` flags of the mappings to the node, similar to every other entity. 
The `edge` node is also refactored to display the `topic filters` flags on the node, as well as the instance name (not yet implemented, replaced by the generic product name)

fix(30538): Improve the combiner visual identity in the workspace

---

modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java

**Motivation**
Resolves #30336
**Changes**
ADS is now only setting the state to connected if we successfully get the connection.
Before that we didn't really check and because of some internal error in PLC4X ( a type cast in case ADS wasn't able to connect ) we never got to see problems occuring.

Error states were incorrectly handled in ADS.

---

hivemq-edge/src/frontend/src/modules/Workspace/types.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/status-utils.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/status-utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/31710/details/
The PR adds missing optional chaining  on accessing a data payload that was also not properly typed. Enough said

fix(31710): Prevent crash with edge status

---

hivemq-edge/build.gradle.kts
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java

When hivemq-edge is included in hivemq-edge-test changes to the protocol adapter modules wouldn't trigger the module to be rebuilt.
Only using includeBuild results in modules not being rebuilt when hivemq-edge is included in other builds.
This is due to a not-declared dependency between the modules and edge.
I made the protocol adapter modules compileOnly depdencies instead of only doing includeBuild which gives gradle the required information to react to changes in the modules.

Added modules as compileOnly dependency to reliably reload changes when testing

---

hivemq-edge/src/frontend/src/components/react-flow/NodeToolbar.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Theme/globals/react-flow.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/ContextualToolbar.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/nodes/NodeAdapter.spec.cy.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/31771/details/
The PR improves. the toolbar in the workspace, to deal with situations when multiple nodes are selected.
- As before, only one toolbar is displayed on the workspace
- When multiple nodes are selected, the toolbar will be displayed on the topmost node, ensuring a better experience 
- The `title` of the toolbar will show either the name of the component (single selection) or a text such as "3 elements selected" (multiple selection)
- Only the CTAs for selection-based commands are shown on the toolbar: `group` and `combine`

fix(31771): Improve the toolbar when multiple nodes are selected

---

hivemq-edge/src/frontend/src/components/rjsf/utils/getChakra.ts
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/AdapterController.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/31834/details/
The PR fixes a problem, whereas navigation to `Adapter`-related pages from the rest of the web app would no work.
The PR also adds toast when the URL used for navigation leads to non-existent adapter or protocol adapters. 
- The main app's routing leads to an error page if the destination doesnt exist. The use of toasts for this case might be revisited in a future ticket.

fix(31834): Fix routing of adapter pages

---

hivemq-edge/src/frontend/src/modules/Workspace/components/ReactFlowWrapper.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/edges/DynamicEdge.tsx
hivemq-edge/src/frontend/src/modules/Workspace/types.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/edge.utils.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/nodes-utils.spec.ts
hivemq-edge/src/frontend/src/modules/Workspace/utils/nodes-utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30497/details/
The PR is the first of a series of improvements on the `Workspace`. 
Its main objective is to improve the readability of the whole graph by removing the fixed top/below layout for (respectively) adapters and bridges and adding dynamic link positioning to support more complex connected configurations. 
- The edge between nodes has been redesigned to support dynamic positioning. 
- An edge will connect to the nearest point  on the boundary of the nodes, rather than using the handles
- The direction of all edges is now clearly visible at the contact points with the nodes they connect with
- "Glued" nodes (for example a device and its adapter) are rendered using a simple half-space approach (above or below the edge node), …

feat(30497): Improve the layout and UX of the workspace

---

.github/workflows/check.yml

See  https://hivemq.kanbanize.com/ctrl_board/57/cards/29697/details/
As part of the build process clean-up, the PR changes the conditions for executing the `CI Check` workflow, only running on push events that include at least one file outside the directory containing the frontend "monorepo".
The change will only affect pure-frontend PRs and will streamline the build process:
- the `check` workflow will not run on the PR without some change on the composite repo
- the `code coverage` report, which only includes backend code and infrastructure, will not be included in frontend tickets, leaving the space for frontend-dedicated code coverage, see https://hivemq.kanbanize.com/ctrl_board/57/cards/31835/details/
The change is matching similar restrictions on frontend-only pipeline that are not …

CI(31985): add path exclusion for the ci-check on frontend

---

hivemq-edge/src/main/java/com/hivemq/combining/runtime/DataCombiningRuntime.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/TagManager.java
hivemq-edge/src/test/java/com/hivemq/edge/modules/adapters/data/TagManagerTest.java

**Motivation**
Resolves #31949
**Changes**
When a new tag value came in we iterated over all consumers to inform them about the new value.
A broken consumer could throw an exception which would stop the iteration.
The fix is to catch and report the errors and then continue processing.

Fixed cases where processing stopped because of a broken consumer

---

.github/workflows/frontend-cli.yml
hivemq-edge/src/frontend/src/components/ErrorMessage.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useValidateCombiner.spec.ts
hivemq-edge/src/frontend/src/modules/Metrics/MetricsContainer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Metrics/MetricsContainer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/controls/NodePanelController.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/GroupPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/LinkPropertyDrawer.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/drawers/LinkPropertyDrawer.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/edges/DynamicEdge.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Workspace/components/edges/DynamicEdge.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/32008/details/
The PR adds support for "Observability" from the new dynamic links in the workspace

fix(32008): Fix access to Observability from links

---

hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Mappings/combiner/DataCombiningEditorField.tsx
hivemq-edge/src/frontend/src/modules/Mappings/combiner/components/AutoMapping.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Mappings/combiner/components/AutoMapping.tsx
hivemq-edge/src/frontend/src/modules/Mappings/combiner/components/ClearMappings.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Mappings/combiner/components/ClearMappings.tsx
hivemq-edge/src/frontend/src/modules/Mappings/utils/combining.utils.spec.ts
hivemq-edge/src/frontend/src/modules/Mappings/utils/combining.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/31587/details/
The PR adds the option for the end-user to generate some suggested mappings for the instructions. Suggestion are made by finding the best match between properties on the sources and properties on the destination sides of the combiner.
- Matching is determined by the similarity between the names of the properties, ensuring equality of type.
- The similarity is computed by the Levenshten string metrics
- A threshold is defined internally for the  best find
- The process used ensures that the best match, regardless of the threshold will be proposed
- The parameters of the matching routine are hard-coded. There is some value in allowing end-users to specify different values, it will be done in subsequent ticket

feat(31587): Add auto mapping assignment to the combiner

---

hivemq-edge/src/frontend/src/modules/Mappings/CombinerMappingManager.tsx
hivemq-edge/src/frontend/src/modules/Mappings/combiner/DataCombiningEditorDrawer.tsx
hivemq-edge/src/frontend/src/modules/Mappings/combiner/DataCombiningEditorField.tsx
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useValidateCombiner.spec.ts
hivemq-edge/src/frontend/src/modules/Mappings/hooks/useValidateCombiner.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/31360/details/
The PR add custom validations to the `Combiner`'s mapping editor.
It ensures that individual mappings are validated in the editor the same way they are all validated in the complete `Combiner`.

fix(31360): Add custom validation to the Combiner's mapping editor

---

hivemq-edge/src/frontend/src/__test-utils__/rjsf/CustomFormTesting.tsx
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/Device/components/DeviceTagList.tsx
hivemq-edge/src/frontend/src/modules/Device/components/TagTableField.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/Device/components/TagTableField.tsx
hivemq-edge/src/frontend/src/modules/Device/hooks/useTagManager.spec.ts
hivemq-edge/src/frontend/src/modules/Device/hooks/useTagManager.ts
hivemq-edge/src/frontend/src/modules/Device/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/31787/details/
The PR fixes a bug, whereas a device with no `WRITE` capability would still show the writing schemas in the list of `tags`

fix(31787): Prevent non-WRITE adapter to access tag schemas

---

hivemq-edge-frontend/src/components/Modal/ConfirmationDialog.spec.cy.tsx
hivemq-edge-frontend/src/components/Modal/ConfirmationDialog.tsx
hivemq-edge-frontend/src/extensions/datahub/components/pages/DataHubListings.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/components/pages/DataHubListings.tsx
hivemq-edge-frontend/src/extensions/datahub/locales/en/datahub.json

See https://hivemq.kanbanize.com/ctrl_board/57/cards/32892/details/
The PR refactors the delete modal for `Script` and `Schema`, highlighting the fact that EVERY version of the selected resource will be deleted 
- The display of the resources, as a "bundle" of several versions, will be dealt with in a subsequent ticket. See https://hivemq.kanbanize.com/ctrl_board/57/cards/32894/details/
- The confirmation modal needs refactoring to handle different types of content

feat(32892): Confirm the deletion of all versions of a script or schema

---

ext/hivemq-edge-openapi-2025.9-SNAPSHOT.yaml
ext/openAPI/components/schemas/BehaviorPolicyTransitionEvent.yaml
ext/openAPI/components/schemas/FunctionMetadata.yaml
ext/openAPI/components/schemas/FunctionSpecs.yaml
ext/openAPI/components/schemas/FunctionSpecsList.yaml
ext/openAPI/openapi.yaml
ext/openAPI/paths/api_v1_data-hub_function-specs.yaml
ext/openAPI/paths/api_v1_data-hub_functions.yaml

See https://hivemq.kanbanize.com/ctrl_board/57/cards/33305/details/
The PR proposes a different implementation of the API endpoints, delivering the list of functions to the Datahub Designer. The API was designed to replace the hard-coded elements in the frontend, but was never utilised.
The existing APi, `GET   /api/v1/data-hub/functions` returns a complete JSON-Schema of every function in the system but suffers from a few flaws:
- It includes the user-defined transformation functions
- As a JSON-Schema block, it is expected to be used as such (e.g. in a form with RJSF) but cannot be reused in other elements (e.g. in a selector)
- It contains the metadata as an undocumented property of JSON-Schema
- It cannot be filtered out easily 
The PR deprecates the old endpoint to add a new …

refactor(33305): Redesign the openAPI specs for the datahub functions

---

hivemq-edge-frontend/src/extensions/datahub/components/controls/DesignerToolbox.tsx
hivemq-edge-frontend/src/extensions/datahub/components/controls/ToolItem.tsx
hivemq-edge-frontend/src/extensions/datahub/components/controls/ToolboxNodes.tsx
hivemq-edge-frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
hivemq-edge-frontend/src/extensions/datahub/utils/datahub.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29930/details/
The PR fixes a bug with the toolbox dropdown, not properly closing when dragging an item on the `Designer` canvas. The bug also has an effect on the ability to operate the DnD in Cypress-based tests
The dropdown now closes at the onset of the drag-and-drop operation, clearing the canvas of all obstacles
The PR also fixes a potential bug with the DnD transfer data not being cleared after usage or cancellation.

fix(29930): Fix the toolbox dropdown not closing

---

hivemq-edge-frontend/src/components/rjsf/Form/validation.utils.ts
hivemq-edge-frontend/src/extensions/datahub/api/__generated__/schemas/BehaviorPolicyData.json
hivemq-edge-frontend/src/extensions/datahub/components/forms/CodeEditor.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/components/forms/ReactFlowSchemaForm.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicyPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicyPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicySchema.ts
hivemq-edge-frontend/src/extensions/datahub/designer/operation/OperationPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge-frontend/src/extensions/datahub/types.ts
hivemq-edge-frontend/src/extensions/datahub/utils/node.utils.ts

see https://hivemq.kanbanize.com/ctrl_board/57/cards/24801/details/
The PR fixes some of the bugs preventing the validation of a behaviour policy 
- Illegal functions: events are used to filter invalid functions in the first place
- illegal value: the design of the ' maxPublish` option has been fixed
The custom format validation has also been added to the policy check, ensuring proper verification of string-based elements such as topics, interpolations, etc. 
See also https://github.com/hivemq/hivemq-edge-commercial-modules/pull/166
- The exact design of the `maxFunction` will need to change in the backend; it will be done in a subsequent ticket

fix(24801): Fix error with the validation of behavior policies

---

hivemq-edge-frontend/src/__test-utils__/hooks/WrapperAccessibleDraggableProvider.tsx
hivemq-edge-frontend/src/extensions/datahub/__test-utils__/transform.mocks.ts
hivemq-edge-frontend/src/extensions/datahub/__test-utils__/vitest.utils.ts
hivemq-edge-frontend/src/extensions/datahub/components/pages/DataHubListings.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicyNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/designer/client_filter/ClientFilterNode.utils.spec.ts
hivemq-edge-frontend/src/extensions/datahub/designer/client_filter/ClientFilterNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/designer/data_policy/DataPolicyNode.utils.spec.ts
hivemq-edge-frontend/src/extensions/datahub/designer/data_policy/DataPolicyNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/designer/operation/OperationNode.utils.spec.ts
hivemq-edge-frontend/src/extensions/datahub/designer/operation/OperationNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.spec.ts
hivemq-edge-frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/designer/schema/SchemaPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/script/FunctionNode.utils.spec.ts
hivemq-edge-frontend/src/extensions/datahub/designer/script/FunctionNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/designer/script/FunctionPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/topic_filter/TopicFilterNode.utils.spec.ts
hivemq-edge-frontend/src/extensions/datahub/designer/topic_filter/TopicFilterNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/designer/transition/TransitionNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.spec.ts
hivemq-edge-frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.ts
hivemq-edge-frontend/src/extensions/datahub/hooks/usePolicyDryRun.spec.ts
hivemq-edge-frontend/src/extensions/datahub/hooks/usePolicyDryRun.ts
hivemq-edge-frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge-frontend/src/extensions/datahub/utils/theme.utils.spec.ts
hivemq-edge-frontend/src/hooks/useAccessibleDraggable/useAccessibleDraggable.spec.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/29734/details/
The PR fixes a series of different issues that prevented policies, both Data and Behaviour, from being properly published. Most of the errors resolve around the use of multiple resources at a given point, e.g. multiple schemas with the same (or different) name (or version) in a validator. 
- The loaded elements of a policy have a proper UUID assigned to their node (with a type-based prefix)
- The determination of connected nodes now correctly handles version, source and target  
- Function name and version are now properly handled, from `1` to `latest`
- The detection of a script or schema version at load time is now properly identifying multiple versions of the same resource
The changes introduce a strong identification …

fix(29734): Fix a series of bugs when publishing policies with multiple resources 

---

hivemq-edge-frontend/src/extensions/datahub/designer/schema/SchemaPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/script/FunctionPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/utils/policy.utils.spec.ts
hivemq-edge-frontend/src/extensions/datahub/utils/policy.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/33994/details/
The PR fixes a small bug when resources (script and schema) are loaded and their configuration panel is opened for the first time. Both name and version are now properly detected and instantiated

fix(33994): Fix persistence with name and version of resources

---

hivemq-edge-frontend/src/extensions/datahub/components/toolbar/ToolbarPublish.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/components/toolbar/ToolbarPublish.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/33943/details/
The Pr fixes a destructive behaviour, where a policy publish request might fail but the resources contained will be published. The policy, as displayed in the `Designer` is therefore wrong
The publish process was redesigned to change, on the success of the requests, the status of resource nodes from `DRAFT` to `PUBLISHED`. This "optimistic" update has two advantages
- if the whole policy is successfully published, the automatic reloading of the `Designer` will recreate the policy from a clean slate
- If the policy fails however, the draft is still valid, ready for potential correction since the various resources have now all been converted to an existing saved script (or schema)
The PR also refactors the handling of …

refactor(33943): Implement optimistic policy nodes update

---

hivemq-edge-frontend/cypress/support/commands.ts
hivemq-edge-frontend/package.json
hivemq-edge-frontend/pnpm-lock.yaml
hivemq-edge-frontend/src/extensions/datahub/api/hooks/DataHubFunctionsService/__handlers__/index.ts
hivemq-edge-frontend/src/extensions/datahub/components/controls/PropertyPanelController.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicyPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicyPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/client_filter/ClientFilterPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/client_filter/ClientFilterPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/data_policy/DataPolicyPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/data_policy/DataPolicyPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/operation/OperationPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/operation/OperationPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/schema/SchemaPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/schema/SchemaPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/script/FunctionPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/script/FunctionPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/topic_filter/TopicFilterPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/topic_filter/TopicFilterPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/transition/TransitionPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/transition/TransitionPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/validator/ValidatorPanel.spec.cy.tsx
hivemq-edge-frontend/src/extensions/datahub/designer/validator/ValidatorPanel.tsx
hivemq-edge-frontend/src/extensions/datahub/types.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/34191/details/
The PR adds the missing loading state and error management for all the policy node's configuration panels. It will prevent many JSON Schema-based forms from being displayed when required validation elements are not fully or properly loaded.
- The error messages are mostly in a non-user-friendly state. They will be fixed as part of the Problem Detail initiative

refactor(34191): Improve loading and error management in the configuration panels

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaClientConnection.java

**Motivation**
Resolves #34450
**Changes**
Select an endpoint based on the configured security policy instead of just picking the first one.

Seelct the correct endpoint instead of picking the 1st

---

hivemq-edge/src/main/java/com/hivemq/bridge/BridgeService.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/BridgeExtractor.java

**Motivation**
Resolves #34787
**Changes**
Editing a bridge via the UI would lead to a broken bridge.
Breakage happened because the client wasn't correctly stopped.
This PR reworks the bridge restart code and fixes the issue by correctly stopping the existing bridge and then restarzing it.

Rework bridge handling to fix a bug

---

hivemq-edge/src/main/java/com/hivemq/api/model/adapters/AdapterStatusModelConversionUtils.java
hivemq-edge/src/main/java/com/hivemq/configuration/ConfigurationBootstrap.java
hivemq-edge/src/main/java/com/hivemq/configuration/EnvironmentVariables.java
hivemq-edge/src/main/java/com/hivemq/configuration/SystemProperties.java
hivemq-edge/src/main/java/com/hivemq/configuration/info/SystemInformation.java
hivemq-edge/src/main/java/com/hivemq/configuration/info/SystemInformationImpl.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java
hivemq-edge/src/main/java/com/hivemq/util/render/FileFragmentUtil.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/AbstractConfigurationTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ConfigFileReaderTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ConfigFileReaderWriterTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ProtocolAdapterExtractorTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/writer/AbstractConfigWriterTest.java
hivemq-edge/src/test/java/com/hivemq/edge/modules/adapters/simulation/config/SimulationProtocolAdapterConfigTest.java
hivemq-edge/src/test/java/com/hivemq/util/render/FileFragmentUtilTest.java
modules/hivemq-edge-module-etherip/src/test/java/com/hivemq/edge/adapters/etherip/config/EipProtocolAdapterConfigTest.java
modules/hivemq-edge-module-file/src/test/java/com/hivemq/edge/adapters/file/config/FileProtocolAdapterConfigTest.java
modules/hivemq-edge-module-http/src/test/java/com/hivemq/edge/adapters/http/config/HttpProtocolAdapterConfigTest.java
modules/hivemq-edge-module-modbus/src/test/java/com/hivemq/edge/adapters/modbus/config/ModbusProtocolAdapterConfigTest.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/config/OpcUaProtocolAdapterConfigTest.java
modules/hivemq-edge-module-plc4x/src/test/java/com/hivemq/edge/adapters/plc4x/types/ads/config/ADSProtocolAdapterConfigTest.java
modules/hivemq-edge-module-plc4x/src/test/java/com/hivemq/edge/adapters/plc4x/types/siemens/config/S7ProtocolAdapterConfigTest.java

**Motivation**
Resolves #34792
**Changes**
Fragments (parts of the config stored in configmaps in k8s) can now be zipped.

Added support for zipping fragment content in k8s

---

hivemq-edge-frontend/src/modules/Bridges/components/BridgeEditorDrawer.spec.cy.tsx
hivemq-edge-frontend/src/modules/Bridges/components/BridgeStatusContainer.spec.cy.tsx
hivemq-edge-frontend/src/modules/Bridges/components/BridgeStatusContainer.tsx
hivemq-edge-frontend/src/modules/Bridges/components/BridgeTable.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/35003/details/
The PR fixes a bug, whereas the list of bridges displayed on the landing page does not update its status, unlike the live adapter page. 
- The status of an adapter is still incorrect in many cases. It will be fixed in further tickets

fix(35003): Update bridge status in the landing page

---

hivemq-edge-frontend/src/api/schemas/bridge.json-schema.ts
hivemq-edge-frontend/src/modules/Bridges/components/BridgeEditorDrawer.spec.cy.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/35265/details/
The PR fixes a bug in the Bridge subscriptions, preventing end-users from utilising interpolation strings (such as `{#}`). Note that the "fix" consists of removing the custom validation of MQTT topics, therefore allowing users to type incorrect topics. 
- The fix removes the `mqtt-topic` format for the string, disabling the validation of an MQTT topic (hence the problem with the wildcard `'#`). This weakens the validation of a bridge and will need to be reintroduced in a subsequent ticket.
- The interpolation patterns are not fully documented. The re-implementation of a properly validated topic + interpolation (e.g. `mqtt-topic-interpolation`) will need to be designed and implemented properly for both backend and frontend

fix(35265): Fix bug with interpolation in the Bridge's subscription destinations

---

ext/hivemq-edge-openapi-2025.14-SNAPSHOT.yaml
ext/openAPI/components/schemas/PulseStatus.yaml

See https://hivemq.kanbanize.com/ctrl_board/57/cards/35484/details/
The PR fixes a bug with the PulseStatus stubs in the frontend and simplify the structure of the payload, to align with the other statuses in Edge

fix(35484): Fix bug with the Pulse Status

---

modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java

**Motivation**
Resolves #35888
We discovered that ADS sometimes gets "stuck".
Turns out PLC4X sometimes fails to react properly to a broken ADS connection.
This happens when the connection is being acquired and blocks on 
`plcDriverManager.getConnectionManager().getConnection(connectionString)`
This block doesn't time out and essentially breaks any fruther attempt.
**Changes**
Add logging that indicates the requirement for a restart when the call doesn't return.

Added log messages for ADS failures since some require an edge restart

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaClientConnection.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/listeners/OpcUaSubscriptionListener.java

**Motivation**
We saw tags being sent north twice instead of one time
**Changes**
With a rapid succession of restarts it could happen that a connection wasn't closed correctly, leading to multiple reads of the same tag happening in parallel.

Fixed a situation where rappidly restarting the adapter could lead to two open clients producing multiple tag reads

---

hivemq-edge-frontend/src/components/PaginatedTable/components/Filter.tsx
hivemq-edge-frontend/src/components/PaginatedTable/types.ts
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetsTable.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/35449/details/
The PR improves the rendering of column-based filters by enabling custom components of the React Select widget in the column specification of a paginated table 
The feature is applied to the `Asset` status filter, where the values in the filter are now properly rendered as the visual tag, rather than the internal value (string)

feat(35496): Add custom renderer for the table filters

---

hivemq-edge-frontend/src/modules/Mappings/combiner/DataCombiningTableField.spec.cy.tsx
hivemq-edge-frontend/src/modules/Mappings/combiner/DataCombiningTableField.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetNameCell.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetNameCell.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetsTable.spec.cy.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/36222/details/
The PR fixes the following issues in the `asset mapping` list in the `Asset Mapper `:
- the headers of the columns
- the rendering of the `asset name` cells

fix(36222) Fix the headers in the mapper's mappings list

---

hivemq-edge-frontend/cypress/e2e/pulse/activation.spec.cy.ts
hivemq-edge-frontend/src/api/hooks/usePulse/useGetPulseStatus.spec.ts
hivemq-edge-frontend/src/api/hooks/usePulse/useListManagedAssets.spec.ts
hivemq-edge-frontend/src/api/hooks/usePulse/useListManagedAssets.ts
hivemq-edge-frontend/src/extensions/datahub/components/pages/SchemaTable.copilot.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetMapperWizard.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetMonitoringBadge.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetMonitoringBadge.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetMonitoringOnboardingTask.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetNameCell.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/AssetsTable.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/ManagedAssetDrawer.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/hooks/useListManagedAssetMappings.spec.ts
hivemq-edge-frontend/src/modules/Welcome/WelcomePage.spec.cy.tsx
hivemq-edge-frontend/src/modules/Welcome/components/Onboarding.tsx
hivemq-edge-frontend/src/modules/Welcome/hooks/useOnboarding.spec.ts
hivemq-edge-frontend/src/modules/Welcome/hooks/useOnboarding.tsx
hivemq-edge-frontend/src/modules/Workspace/components/nodes/NodeAssets.spec.cy.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/36401/details/ and https://hivemq.kanbanize.com/ctrl_board/57/cards/36412/details/
The PR fixes a few issues with the Pulse integration
- The onboarding todos are now (properly) rendered only when Pulse is activated
- The Asset badge in the navigation link is only rendered when Pulse is activated
- The Pulse GET requests are enabled only when the `pulse-asset-management` capability is present (fix 36412)

fix(36401) Improve the handling of Pulse when (not) activated

---

hivemq-edge-frontend/src/api/hooks/useAssetMapper/useCreateAssetMapper.ts
hivemq-edge-frontend/src/api/hooks/useAssetMapper/useDeleteAssetMapper.ts
hivemq-edge-frontend/src/api/hooks/useAssetMapper/useUpdateAssetMapper.ts
hivemq-edge-frontend/src/api/hooks/usePulse/useCreateManagedAsset.ts
hivemq-edge-frontend/src/api/hooks/usePulse/useDeleteManagedAsset.ts
hivemq-edge-frontend/src/api/hooks/usePulse/useUpdateManagedAsset.ts
hivemq-edge-frontend/src/modules/Mappings/AdapterMappingManager.tsx
hivemq-edge-frontend/src/modules/Mappings/hooks/useValidateCombiner.ts
hivemq-edge-frontend/src/modules/Mappings/utils/combining.utils.ts

See https://hivemq.kanbanize.com/ctrl_board/57/cards/36963/details/
The PR fixes three bugs:
- Fetching the `Tags` of an adapter was based on the wrong `id` (must be an adapter!)
- Associating `Tags` and `integration point` was based on a flawed logic that didn't take into account the possible existence of `Pulse` as a source (`Asset Mappers` are based on `Combiner`) 
- Changes to `Asset Mappers` (update, delete) now trigger the invalidity (i.e. stale state, therefore refetch) of the data store for `Assets`, and vice-versa. This is to ensure that the two connected data sources are kept up-to-date
- The validation of `Combiner` and `Asset Mapper` is based on a flawed process that does not ensure proper identification of data sources and integration points. This will be fixed for both …

fix(36963) Fix bug with tags and asset/mapper query updates
