hivemq/hivemq-edge

hivemq-edge/src/main/java/com/hivemq/http/filters/CorsFilter.java

Per request - the custom header should be added to the expose header.

errata (15441) - Added Expose header

---

hivemq-edge/src/main/java/com/hivemq/api/filter/JWTReissuanceFilterImpl.java

The JWT was erroneously offering renewed tokens throughout an existing tokens life.

fix(15566) - JWT Reissuance filter logic flaw

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/ModuleLoader.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java

We need to allow modules to be worked on in the dev environment without the need to eexport them or run out of the module directory. Therefore we should expose them t

feature(15617) - Module classloader in development workspace

---

.github/workflows/frontend-cli.yml
hivemq-edge/src/frontend/.env.test
hivemq-edge/src/frontend/.npmrc
hivemq-edge/src/frontend/README.md
hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/pnpm-lock.yaml
hivemq-edge/src/frontend/src/__test-utils__/setup.ts
hivemq-edge/src/frontend/src/components/MQTT/Topic.tsx
hivemq-edge/src/frontend/src/components/PasswordInput.tsx
hivemq-edge/src/frontend/src/modules/App/components/ErrorPage.tsx
hivemq-edge/src/frontend/src/modules/Bridges/BridgePage.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/overview/BridgeOverview.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/CustomUserProperties.tsx
hivemq-edge/src/frontend/src/modules/Bridges/components/setup/StepperNavigation.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.tsx
hivemq-edge/src/frontend/src/modules/Dashboard/hooks/useGetNavItems.tsx
hivemq-edge/src/frontend/src/modules/UnifiedNamespace/UnifiedNamespacePage.tsx
hivemq-edge/src/frontend/src/modules/UnifiedNamespace/components/panels/InfoPanel.tsx
hivemq-edge/src/frontend/src/modules/Welcome/components/MetricNameSelector.tsx
hivemq-edge/src/frontend/src/modules/Welcome/hooks/useOnboarding.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/15630/details/
This PR creates a frontend-specific workflow (.github/workflows/frontend-cli.yml) that contains the first group of testing frameworks :
- Code quality checks (ESLint, Prettier)
- Interaction testing (Cypress - Component)
- Scenario testing (Cypress - E2E)
- Visual testing (Percy - integrated within Cypress)
- Unit testing (Vitest)

feat(15630): Add a testing workflow for the frontend repo

---

hivemq-edge/src/frontend/src/api/__generated__/HiveMqClient.ts
hivemq-edge/src/frontend/src/api/__generated__/core/OpenAPI.ts
hivemq-edge/src/frontend/src/api/__generated__/schemas/$Bridge.ts

Version 2023.2 of the openAPI specs

refactor(master): Update the openAPI stubs

---

hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQEdgeHttpServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQRemoteServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/edge/model/HiveMQEdgeEvent.java
hivemq-edge/src/main/java/com/hivemq/edge/utils/HiveMQEdgeEnvironmentUtils.java

Add a PING event to the tracking system. Fix version flaw. Add session token to tracking data and encapsultate the population of this data.

feat(16109): Add PING event to usage data. Include session tracking.

---

hivemq-edge/src/frontend/src/api/__generated__/HiveMqClient.ts
hivemq-edge/src/frontend/src/api/__generated__/core/OpenAPI.ts
hivemq-edge/src/frontend/src/api/__generated__/index.ts
hivemq-edge/src/frontend/src/api/__generated__/services/FrontendService.ts
hivemq-edge/src/frontend/src/api/__generated__/services/GatewayEndpointService.ts

Ready for Maintenance Release (2023.3)
See https://hivemq.kanbanize.com/ctrl_board/57/cards/16099/details/

chore(16099): update OpenAPI stubs

---

hivemq-edge/src/main/java/com/hivemq/mqtt/message/connect/MqttWillPublish.java
hivemq-edge/src/main/java/com/hivemq/mqtt/message/publish/PUBLISH.java
hivemq-edge/src/main/java/com/hivemq/mqtt/message/pubrel/PUBREL.java
hivemq-edge/src/main/java/com/hivemq/mqtt/message/subscribe/Topic.java
hivemq-edge/src/main/java/com/hivemq/persistence/IterablePersistenceEntry.java
hivemq-edge/src/main/java/com/hivemq/persistence/PersistenceEntry.java
hivemq-edge/src/main/java/com/hivemq/persistence/RetainedMessage.java
hivemq-edge/src/main/java/com/hivemq/persistence/clientsession/ClientSession.java
hivemq-edge/src/main/java/com/hivemq/persistence/clientsession/ClientSessionWill.java
hivemq-edge/src/main/java/com/hivemq/persistence/local/memory/ClientQueueMemoryLocalPersistence.java
hivemq-edge/src/main/java/com/hivemq/persistence/local/memory/ClientSessionMemoryLocalPersistence.java
hivemq-edge/src/main/java/com/hivemq/persistence/local/memory/ClientSessionSubscriptionMemoryLocalPersistence.java
hivemq-edge/src/main/java/com/hivemq/util/MemoryEstimator.java
hivemq-edge/src/test/java/com/hivemq/mqtt/message/publish/PUBLISHTest.java
hivemq-edge/src/test/java/com/hivemq/mqtt/message/pubrel/PUBRELTest.java
hivemq-edge/src/test/java/com/hivemq/persistence/local/memory/ClientQueueMemoryLocalPersistenceTest.java
hivemq-edge/src/test/java/com/hivemq/persistence/local/memory/ClientSessionSubscriptionMemoryLocalPersistenceTest.java
hivemq-edge/src/test/java/com/hivemq/util/MemoryEstimatorTest.java

57 - add improvements to com.hivemq.util.ObjectMemoryEstimation

---

ext/hivemq-edge-openapi-2023.5.yaml
hivemq-edge/src/main/java/com/hivemq/api/model/adapters/ProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/api/model/adapters/ProtocolAdapterCategory.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/ProtocolAdapterConstants.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
hivemq-edge/src/test/java/com/hivemq/adapter/AdapterModelConverterTest.java

Categories need enriching with data including displayName, image & description. Ensure the categories are a strong typed entity through the API. 
NOTE: I is PURPOSELY NOT an enum, as this maybe contributed to in the future and we want to ensure backwards compatibility.

feat(16497) - Strong typed categories through the API

---

hivemq-edge/src/main/resources/hivemq-edge-configuration.json
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java

Fixes issue noted in https://github.com/hivemq/hivemq-edge/issues/86

Issue 86 - Modbus naming convention

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterUtils.java
modules/hivemq-edge-module-http/build.gradle.kts
modules/hivemq-edge-module-http/gradle.properties
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConstants.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
modules/hivemq-edge-module-http/src/test/java/com/hivemq/edge/adapters/http/TestHttpAdapterConfig.java
modules/hivemq-edge-module-http/src/test/resources/http-config-empty-header.xml
modules/hivemq-edge-module-http/src/test/resources/http-config-with-headers.xml

Defer to the built in library for validation of types, specifally for URL (URI) fields.

fix(106) - Changed the URL of HTTP adapter to be URI format

---

modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java

Ensure running and reset on start

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaDataValueConsumer.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaSubscriptionConsumer.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/payload/AbstractOpcUaPayloadConverterTest.java

**Changes**
Adds first sample event for OPC UA adapter

adds first sample event for opc ua

---

README.adoc
docs/.gitattributes
docs/edge-intro.gif

The screenshot shows an example user journey, creating a bridge, a protocol adapter, and finally the workspace.
Please watch the video `docs/edge-intro.gif`.

Adds intro video of HiveMQ Edge as simple screencast

---

build.gradle.kts
ext/release-process.txt
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/hooks/useGetUISchema.ts
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/ProtocolAdapterDataSample.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapter.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/model/HttpData.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/model/ModBusData.java
modules/hivemq-edge-module-plc4x/build.gradle.kts
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xDataUtils.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/model/Plc4xAdapterConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/model/Plc4xDataType.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7AdapterConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapter.java
settings.gradle.kts

Fixed many issues with the PLC4x threading model, added transparent typing to the tag addresses, allowed HTTP adapter to optionally read untrusted SSL, exposed S7 adapter, exposes ADB adapter.

feat(17596) - PLC4X threading, S7 connection, ADS adapter, Http Untrusted SSL

---

.github/actions/setup_node/action.yml
.github/workflows/frontend-cli.yml
hivemq-edge/src/frontend/README.md

**Motivation**
See https://hivemq.kanbanize.com/ctrl_board/57/cards/17463/details/
Fix the installation issues regarding Cypress on the CI.

CI / fix cypress binaries

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/config/impl/AbstractProtocolAdapterConfig.java

bugfix > fix behavior change by making fields not mandatory

---

hivemq-edge/src/main/java/com/hivemq/api/ioc/ApiModule.java
hivemq-edge/src/main/java/com/hivemq/api/model/ApiBodyExamples.java
hivemq-edge/src/main/java/com/hivemq/api/model/capabilities/Capability.java
hivemq-edge/src/main/java/com/hivemq/api/model/capabilities/CapabilityList.java
hivemq-edge/src/main/java/com/hivemq/api/model/components/GatewayConfiguration.java
hivemq-edge/src/main/java/com/hivemq/api/resources/FrontendApi.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/FrontendResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/ioc/Injector.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/ioc/Services.java
hivemq-edge/src/main/java/com/hivemq/edge/HiveMQCapabilityService.java
hivemq-edge/src/main/java/com/hivemq/edge/impl/capability/CapabilityServiceImpl.java

Feature: Capability Service

---

hivemq-edge/src/main/java/com/hivemq/bridge/BridgeService.java
hivemq-edge/src/main/java/com/hivemq/bridge/MessageForwarderImpl.java
hivemq-edge/src/main/java/com/hivemq/bridge/MqttForwarder.java
hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/BridgeMqttClient.java
hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/RemoteMqttForwarder.java
hivemq-edge/src/main/java/com/hivemq/configuration/service/InternalConfigurations.java
hivemq-edge/src/test/java/com/hivemq/bridge/mqtt/RemoteMqttForwarderTest.java

Bugfix: Fix missing buffering before first connect of bridge

---

ext/hivemq-edge-openapi-2023.8.yaml

Created the missed openAPI spec for 2023.8 release. I will update the release process accordingly.

fix(): Adds OpenAPI Spec for 2023.8

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/ModuleLoader.java

Cleanup startup log

---

hivemq-edge/src/main/java/com/hivemq/bridge/MessageForwarderImpl.java
hivemq-edge/src/main/java/com/hivemq/bridge/MqttForwarder.java
hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/RemoteMqttForwarder.java
hivemq-edge/src/test/java/com/hivemq/bridge/mqtt/RemoteMqttForwarderTest.java

Bugfix: Fix bridge Buffering

---

hivemq-edge/src/main/java/com/hivemq/HiveMQEdgeMain.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/ClientQueueLocalPersistenceFactory.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/ClientSessionLocalPersistenceFactory.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/ClientSessionSubscriptionLocalPersistenceFactory.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/PublishPayloadPersistenceFactory.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/RetainedMessageLocalPersistenceFactory.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/provider/ClientQueueLocalPersistenceProvider.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/provider/ClientSessionLocalPersistenceProvider.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/provider/ClientSessionSubscriptionLocalPersistenceProvider.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/provider/PublishPayloadPersistenceProvider.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/provider/RetainedMessageLocalPersistenceProvider.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/PersistenceEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/ioc/ConfigurationModule.java
hivemq-edge/src/main/java/com/hivemq/configuration/service/PersistenceConfigurationService.java
hivemq-edge/src/main/java/com/hivemq/configuration/service/impl/PersistenceConfigurationServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/extensions/core/CommercialModuleLoaderDiscovery.java
hivemq-edge/src/main/java/com/hivemq/extensions/core/CoreModuleService.java
hivemq-edge/src/main/java/com/hivemq/extensions/core/CoreModuleServiceImpl.java
hivemq-edge/src/main/resources/config.xsd

Feature: persistence config

---

hivemq-edge/src/main/java/com/hivemq/persistence/InMemoryProducerQueues.java
hivemq-edge/src/main/java/com/hivemq/persistence/SingleWriterService.java

https://hivemq.kanbanize.com/ctrl_board/42/cards/18359/details/

SingleWriterService > Cascade all exceptions that can be thrown during the task execution.

---

README.adoc
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterInformation.java

**Changes**
Promotes S7 and ADS adapter from beta/alpha after testing

remove alpha/beta version from S7 and ADS

---

hivemq-edge/src/main/java/com/hivemq/mqtt/callback/PublishStatusFutureCallback.java
hivemq-edge/src/main/java/com/hivemq/persistence/local/memory/ClientQueueMemoryLocalPersistence.java
hivemq-edge/src/test/java/com/hivemq/mqtt/callback/PublishStatusFutureCallbackTest.java
hivemq-edge/src/test/java/com/hivemq/persistence/local/memory/ClientQueueMemoryLocalPersistenceTest.java

dont decrement reference counts for queued publishes with QoS-0

---

hivemq-edge/src/main/java/com/hivemq/api/ApiResourceRegistry.java
hivemq-edge/src/main/java/com/hivemq/api/CustomJsonProvider.java
hivemq-edge/src/main/java/com/hivemq/api/MarshallingFeature.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/AdapterHandling.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/AdapterHandlingFactory.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/AdapterHandlingProvider.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/HandlerResult.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/ProtocolAdapterInterceptorHandler.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/extensions/core/HandlerService.java
hivemq-edge/src/main/java/com/hivemq/extensions/services/publish/PublishServiceImpl.java

Adapter Handling

---

modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/eip/EIPProtocolAdapter.java

**Changes**
Fix intermittent warnings that can be the result from temporary read timeouts or a restart of the adapter

fix intermittent warnings in adapter

---

hivemq-edge/src/main/java/com/hivemq/persistence/FilePersistence.java

fix obfuscation > fix obfuscation

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
hivemq-edge/src/main/resources/logback.xml
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ab/ABProtocolAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapter.java

Analysed Logging with Standard Adapers Configured. Fixed PLC4X logging level in log config. Ensured HiveMQ log lines were appropriately formatted and reflected at the correct levels.Fixed some incorrect logger use. Applied log level conditionalcheck for high volume code paths.

feat(17757) - Sanitized Logging

---

ext/hivemq-edge-openapi-2024.1.yaml
ext/hivemq-edge-openapi-2024.2.yaml
hivemq-edge/src/main/java/com/hivemq/http/JaxrsObjectMapperProvider.java

Feature/cinamon integrate backend frontend 

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/ModuleLoader.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaClientConfigurator.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaEndpointFilter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/util/KeystoreUtil.java

Bugfix: Fix keystore path being always empty

---

modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSAdapterConfig.java

Fix: ads adapter port config not working

---

hivemq-edge/src/distribution/conf/logback.xml
hivemq-edge/src/main/java/com/hivemq/http/JaxrsHttpServer.java

…ency
**Motivation**
**Changes**

Cleanup for Release Part3

---

ext/hivemq-edge-openapi-2024.3.yaml
hivemq-edge/src/main/java/com/hivemq/HiveMQEdgeMain.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/ioc/Injector.java
hivemq-edge/src/main/java/com/hivemq/extensions/core/CoreModuleService.java
hivemq-edge/src/main/java/com/hivemq/extensions/core/CoreModuleServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/persistence/ioc/PersistenceModule.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/20262/details/

Feature: State API

---

hivemq-edge/src/main/java/com/hivemq/api/ApiResourceRegistry.java
hivemq-edge/src/main/java/com/hivemq/api/error/CustomJsonParseExceptionMapper.java
hivemq-edge/src/main/java/com/hivemq/api/model/bridge/Bridge.java
hivemq-edge/src/main/java/com/hivemq/api/model/core/TlsConfiguration.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/BridgeResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/bridge/BridgeService.java
hivemq-edge/src/main/java/com/hivemq/bridge/config/MqttBridge.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/bridge/MqttBridgeEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/BridgeConfigurator.java
hivemq-edge/src/main/java/com/hivemq/configuration/service/impl/BridgeConfigurationServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/datagov/impl/DataGovernanceServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/http/JaxrsHttpServer.java
hivemq-edge/src/main/resources/config.xsd
hivemq-edge/src/test/resources/test-config.xml

cleanup > fix part 4

---

hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.spec.cy.tsx
hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.spec.cy.tsx

The PR fixes the tests that compared the relative rendering of dates

fix(NO_TICKET): Fix the dater-based test

---

.github/workflows/frontend-cli.yml
hivemq-edge/src/frontend/cypress/e2e/Login/login.spec.cy.ts
hivemq-edge/src/frontend/src/modules/Workspace/components/edges/MonitoringEdge.spec.cy.tsx

Reducing the noise of the CI stdout

ci(cypress): Enable silent mode on Cypress

---

renovate.json5

Renovate: Split Dependency Updates between gradle and npm

---

hivemq-edge/build.gradle.kts
hivemq-edge/gradle.properties
modules/hivemq-edge-module-modbus/build.gradle.kts

fix(deps): update all patch dependencies

---

hivemq-edge/build.gradle.kts
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterSchemaManager.java

revert networknt dependency update

---

hivemq-edge/src/frontend/.prettierignore
hivemq-edge/src/frontend/build.gradle.kts
hivemq-edge/src/frontend/package.json

Fix: Define versions explicitly to avoid compile issue

---

README.adoc

fix(): Update README.adoc

---

README.adoc

improve readme

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterInformation.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/eip/EIPProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterInformation.java

fix(): Updates adapter documentation link

---

hivemq-edge/src/frontend/src/main.tsx

**Motivation**
The React app doesn't have a page on /, the user needs to go to /app
**Changes**
Automatically redirect / to /app

fix: automatically redirect / to /app

---

hivemq-edge/src/main/java/com/hivemq/api/model/adapters/ProtocolAdapter.java
hivemq-edge/src/main/java/com/hivemq/api/model/components/Module.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdapterApiUtils.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
hivemq-edge/src/main/resources/simulation-adapter-ui-schema.json
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/ProtocolAdapterApiUtilsTest.java
modules/hivemq-edge-module-http/build.gradle.kts
modules/hivemq-edge-module-http/gradle.properties
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterInformation.java
modules/hivemq-edge-module-http/src/main/resources/http-adapter-ui-schema.json
modules/hivemq-edge-module-modbus/build.gradle.kts
modules/hivemq-edge-module-modbus/gradle.properties
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java
modules/hivemq-edge-module-modbus/src/main/resources/modbus-adapter-ui-schema.json
modules/hivemq-edge-module-opcua/build.gradle.kts
modules/hivemq-edge-module-opcua/gradle.properties
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterInformation.java
modules/hivemq-edge-module-opcua/src/main/resources/opcua-adapter-ui-schema.json
modules/hivemq-edge-module-plc4x/build.gradle.kts
modules/hivemq-edge-module-plc4x/gradle.properties
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/eip/EIPProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/resources/ads-adapter-ui-schema.json
modules/hivemq-edge-module-plc4x/src/main/resources/eip-adapter-ui-schema.json
modules/hivemq-edge-module-plc4x/src/main/resources/s7-adapter-ui-schema.json

https://hivemq.kanbanize.com/ctrl_board/57/cards/22339/details/
**Motivation**
**Changes**

Feature/22339 UI schema

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdapterApiUtils.java

fix default ui-schema

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterWrapper.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/22905/details/

Fix discovery

---

hivemq-edge/src/frontend/src/modules/Welcome/components/Onboarding.tsx

**Motivation**
- Browser warning on console when non-unique values are used as map keys
**Changes**
- Adds labels to the keys

[Minor Fix]: Fixes non-unique keys on map

---

modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/config/ContentType.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/config/FileAdapterConfig.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/config/FilePollingContext.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/payload/FilePayload.java
modules/hivemq-edge-module-file/src/main/resources/file-adapter-ui-schema.json

File adapter improvements

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterFactory.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/OpcUaConfigConverterTest.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/OpcUaEndpointFilterTest.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterAuthTest.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/payload/OpcUaJsonPayloadConverterTest.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/payload/OpcUaStringPayloadConverterTest.java

https://hivemq.kanbanize.com/ctrl_board/22/cards/24367/details/

[latest] cleanup-opcua-code

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterWrapper.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/23769/details/
**Motivation**
**Changes**

file adapter > fix discovery api

---

modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/model/HttpData.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/model/HttpPollingContextImpl.java
modules/hivemq-edge-module-http/src/test/java/com/hivemq/edge/adapters/http/HttpAdapterConfigTest.java
modules/hivemq-edge-module-http/src/test/resources/http-config-destination-null.xml
modules/hivemq-edge-module-http/src/test/resources/http-config-empty-header.xml
modules/hivemq-edge-module-http/src/test/resources/http-config-id-null.xml
modules/hivemq-edge-module-http/src/test/resources/http-config-url-null.xml
modules/hivemq-edge-module-http/src/test/resources/http-config-with-headers.xml

https://hivemq.kanbanize.com/ctrl_board/22/cards/24501/details/

[latest] http-protocol-adapter-config

---

hivemq-edge/src/main/java/com/hivemq/configuration/reader/ArbitraryValuesMapAdapter.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ConfigFileReaderTest.java
modules/hivemq-edge-module-modbus/src/test/java/com/hivemq/edge/adapters/modbus/ModbusAdapterConfigTest.java
modules/hivemq-edge-module-modbus/src/test/resources/modbus-adapter-full-config.xml

https://hivemq.kanbanize.com/ctrl_board/22/cards/24704/details/

[latest] user-propertie

---

gradle.properties
hivemq-edge/gradle.properties
modules/hivemq-edge-module-etherip/gradle.properties
modules/hivemq-edge-module-file/gradle.properties
modules/hivemq-edge-module-http/gradle.properties
modules/hivemq-edge-module-modbus/gradle.properties
modules/hivemq-edge-module-opcua/gradle.properties
modules/hivemq-edge-module-plc4x/gradle.properties

version to 2024.8-SNAPSHOT

---

hivemq-edge/src/main/resources/config.xsd

add queue-limit to config.xsd

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaEndpointFilter.java

**Motivation**
Resolves #26404
We were missing quite some logging to see the state of OPC-UA connections.
**Changes**
- Add more logging to OPC-UA
- Fix some missing Thread-interrupt handling

Added more logging for OPC-UA and fixed some missing interrupts

---

edge-plugins/build.gradle.kts
edge-plugins/src/main/kotlin/com/hivemq/licensethirdparty/DependencyReport.kt
edge-plugins/src/main/kotlin/com/hivemq/licensethirdparty/License.kt
edge-plugins/src/main/kotlin/com/hivemq/licensethirdparty/ThirdPartyLicenseGeneratorPlugin.kt
edge-plugins/src/main/kotlin/com/hivemq/licensethirdparty/UpdateThirdPartyLicensesTask.kt
hivemq-edge/build.gradle.kts
modules/hivemq-edge-module-etherip/build.gradle.kts
modules/hivemq-edge-module-file/build.gradle.kts
modules/hivemq-edge-module-http/build.gradle.kts
modules/hivemq-edge-module-modbus/build.gradle.kts
modules/hivemq-edge-module-opcua/build.gradle.kts
modules/hivemq-edge-module-plc4x/build.gradle.kts

https://hivemq.kanbanize.com/ctrl_board/57/cards/26733/details/

fix third party license generation

---

edge-plugins/gradle.properties
hivemq-edge/gradle.properties
modules/hivemq-edge-module-etherip/gradle.properties
modules/hivemq-edge-module-file/gradle.properties
modules/hivemq-edge-module-http/gradle.properties
modules/hivemq-edge-module-modbus/gradle.properties
modules/hivemq-edge-module-opcua/gradle.properties
modules/hivemq-edge-module-plc4x/gradle.properties

**Motivation**
gradle.properties are not inherited with includeBuild, only with include
**Changes**
Readd gradle.properties to all projects

Readding gradle.properties

---

modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterFactory.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/ModbusAdu.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/ModbusToMqttMapping.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/tag/ModbusTagDefinition.java

**Changes**
We decided to merge addressRange and ModbusTagDefinition.

Moved content of addressRange into modbustagdefinition

---

ext/hivemq-edge-openapi-2024.8-SNAPSHOT.yaml
hivemq-edge/src/main/java/com/hivemq/api/model/adapters/Adapter.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/26764/details/

Fix Swagger plugin generating unusable OpenAPI

---

hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/27878/details/

fix serialization of tags and adapter config

---

ext/hivemq-edge-openapi-2024.8-SNAPSHOT.yaml
hivemq-edge/src/main/java/com/hivemq/api/json/CustomConfigSchemaGenerator.java
hivemq-edge/src/main/java/com/hivemq/api/model/tags/TagSchema.java
hivemq-edge/src/main/java/com/hivemq/api/resources/ProtocolAdaptersApi.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/test/java/com/hivemq/adapter/TagSchemaNodeGeneratorTest.java

**Motivation**
Resolves #27902
**Changes**
Added endpoint **/tagschemas/{protocolId}** which gives access to the schema of the tag type used for the specified protocol adapter.

Added an endpoint for accessing shcemas for individal tag types

---

modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/EipPollingProtocolAdapter.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/EipProtocolAdapterFactory.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/config/EipToMqttMapping.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/config/tag/EipTagDefinition.java
modules/hivemq-edge-module-etherip/src/test/java/com/hivemq/edge/adapters/etherip/EipPollingProtocolAdapterIT.java
modules/hivemq-edge-module-etherip/src/test/java/com/hivemq/edge/adapters/etherip/config/EipAdapterConfigTest.java
modules/hivemq-edge-module-etherip/src/test/java/com/hivemq/edge/adapters/etherip/config/legacy/LegacyEipAdapterConfigTest.java
modules/hivemq-edge-module-etherip/src/test/resources/eip-adapter-full-config.xml
modules/hivemq-edge-module-etherip/src/test/resources/eip-adapter-minimal-config.xml

**Motivation**
Resolves #27856
**Changes**
Move EipDatatype from mapping into EipTagDefinition

Move datatype into tag

---

ext/hivemq-edge-openapi-2024.8-SNAPSHOT.yaml
hivemq-edge/src/main/java/com/hivemq/api/resources/ProtocolAdaptersApi.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
hivemq-edge/src/main/java/com/hivemq/util/ErrorResponseUtil.java

**Motivation**
Adds an endpoint to load a single tag by name to make testing easier.

Added the capability to load a single Tag to the API

---

ext/hivemq-edge-openapi-2024.8-SNAPSHOT.yaml
hivemq-edge/src/main/java/com/hivemq/api/model/tags/DomainTagModel.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/SamplingResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/tag/SimulationTag.java
hivemq-edge/src/main/java/com/hivemq/persistence/domain/DomainTag.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
hivemq-edge/src/test/java/com/hivemq/adapter/TagSchemaNodeGeneratorTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImplTest.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/config/tag/EipTag.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/tag/FileTag.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/tag/HttpTag.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/tag/ModbusTag.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/tag/OpcuaTag.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/config/tag/Plc4xTag.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/28250/details/

Frontend Integration - Part2

---

hivemq-edge/src/main/java/com/hivemq/HiveMQEdgeMain.java
hivemq-edge/src/main/java/com/hivemq/configuration/migration/ConfigurationMigrator.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/ModuleLoader.java
hivemq-edge/src/main/java/com/hivemq/embedded/internal/EmbeddedHiveMQImpl.java
hivemq-edge/src/main/java/com/hivemq/extensions/core/CommercialModuleLoaderDiscovery.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/28569/details/

fix duplicate loading of modules when loadModules() is called twice

---

modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/EipProtocolAdapterInformation.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/FileProtocolAdapterInformation.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterInformation.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapterInformation.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterInformation.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/26206/details/

Update opcua description

---

hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java

**Changes**
Message expiry method wasnÄT overridden.

Expire method wasn't overridden

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java

fix wrong composition of mappings

---

ext/hivemq-edge-openapi-2024.8-SNAPSHOT.yaml
hivemq-edge/src/main/java/com/hivemq/api/resources/SamplingApi.java
hivemq-edge/src/main/java/com/hivemq/api/resources/TopicFilterApi.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/SamplingResourceImpl.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/28666/details/

Replace base64 with uri encoding in the Sampling API

---

hivemq-edge/src/main/java/com/hivemq/api/model/JavaScriptConstants.java
hivemq-edge/src/main/java/com/hivemq/api/model/mappings/northbound/NorthboundMappingModel.java
hivemq-edge/src/test/java/com/hivemq/api/model/mappings/northbound/NorthboundMappingModelTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/28661/details/

Add translation to JS max safe value for message expiry and back

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaDataValueConsumer.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/opcua2mqtt/OpcUaJsonPayloadConverter.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/28714/details/

Added timestamp and tagName inclusion feature for OPCUA

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaClientWrapper.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/OpcUaSpecificAdapterConfig.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/tag/OpcuaTagDefinition.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/mqtt2opcua/JsonSchemaGenerator.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/28681/details/

Feature/28681: Improve Error Messages

---

hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterFactoryManager.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/EipProtocolAdapterInformation.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/FileProtocolAdapterInformation.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterInformation.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/28957/details/

add logic to resolve legacy protocol ids

---

hivemq-edge/src/main/java/com/hivemq/configuration/migration/ConfigurationMigrator.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/ArbitraryValuesMapAdapter.java

https://hivemq.kanbanize.com/ctrl_board/57/

start to fix migration

---

hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
hivemq-edge/src/frontend/src/locales/en/translation.json
hivemq-edge/src/frontend/src/modules/ProtocolAdapters/ProtocolAdapterPage.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/UnifiedNamespace/components/panels/InfoPanel.tsx
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
hivemq-edge/src/main/resources/hivemq-edge-configuration.json

The PR text improvements provided by Mary.
https://hivemq.kanbanize.com/ctrl_board/57/cards/29818/details/

fix(): Improve texts of protocol adapters descriptions

---

docker/config-k8s.xml

Persistence type for K8s

---

docker/config-k8s.xml

fix env var

---

gradle/libs.versions.toml

revert dependency update

---

hivemq-edge/src/main/java/com/hivemq/HiveMQEdgeBootstrap.java
hivemq-edge/src/main/java/com/hivemq/configuration/migration/ConfigurationMigrator.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/29055/details/

reduce log verbosity at startup

---

hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/src/api/__generated__/HiveMqClient.ts
hivemq-edge/src/frontend/src/api/__generated__/core/OpenAPI.ts
hivemq-edge/src/frontend/src/modules/Bridges/components/panels/BridgeEditor.tsx
hivemq-edge/src/frontend/src/modules/Bridges/hooks/useBridgeConfig.tsx
hivemq-edge/src/frontend/src/modules/Bridges/utils/defaults.utils.ts
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/BridgeResourceImpl.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/30106/details/

Fix NPE in bridge

---

hivemq-edge/src/distribution/bin/run.sh

**Motivation**
https://hivemq.kanbanize.com/ctrl_board/57/cards/30206/details/
**Changes**

Data Hub: Port env variable to prevent SIGSEGV

---

build.gradle.kts
docker/logback-k8s.xml

https://hivemq.kanbanize.com/ctrl_board/57/cards/30221/details/

add default logback to k8s

---

.github/workflows/check.yml
.github/workflows/etherip-package.yml
edge-plugins/build.gradle.kts
hivemq-edge/build.gradle.kts
modules/hivemq-edge-module-etherip/build.gradle.kts
modules/hivemq-edge-module-file/build.gradle.kts
modules/hivemq-edge-module-http/build.gradle.kts
modules/hivemq-edge-module-modbus/build.gradle.kts
modules/hivemq-edge-module-opcua/build.gradle.kts
modules/hivemq-edge-module-plc4x/build.gradle.kts

**Motivation**
Resolves #30163
**Changes**
JDK 17 is our new baseline.

Upgrade compile target to JDK 17

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/BridgeResourceImpl.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/30303/details/

fix wrong check leading to subscription not being applied

---

hivemq-edge/src/main/java/com/hivemq/extensions/HiveMQExtensions.java
hivemq-edge/src/main/java/com/hivemq/util/Checkpoints.java

add exrebsio
**Motivation**
**Changes**

Improve Checkpoint usage

---

hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/components/MappingEditor.spec.cy.tsx
hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/components/MappingInstructionList.tsx

redo https://github.com/hivemq/hivemq-edge/pull/832

fix(30892) fix-property-list

---

hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/components/MappingInstructionList.tsx
hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/components/mapping/MappingInstruction.tsx
hivemq-edge/src/frontend/src/components/rjsf/MqttTransformation/components/schema/PropertyItem.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/30920/details/
The PR fixes a bug preventing instruction to show and persist their full path

fix(30920): Fix bug with full path in instruction

---

hivemq-edge/src/main/java/com/hivemq/combining/runtime/DataCombiningRuntime.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/EipPollingProtocolAdapter.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/PublishChangedDataOnlyHandler.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/model/EtherIpValueFactory.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/payload/FileDataPoint.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/PublishChangedDataOnlyHandler.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/ModbusSpecificAdapterConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/PublishChangedDataOnlyHandler.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
modules/hivemq-edge-module-plc4x/src/test/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterTest.java

**Motivation**
Resolves #30618
**Changes**
- EthernetIP Adapter publishChangedDataOnly fixed
- Modbus Adapter publishChangedDataOnly fixed
- File Adapter publishChangedDataOnly fixed

Fix changedataonly for the adapters supporting it

---

hivemq-edge/src/main/java/com/hivemq/combining/runtime/SourceSanitizer.java

Fix handling of the $. prefix introduced in the rc.

Fix datahub prefix handling

---

hivemq-edge/src/main/java/com/hivemq/edge/modules/ModuleLoader.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/31149/details/

fix module loader not working on work space

---

hivemq-edge/src/main/java/com/hivemq/combining/model/DataCombining.java
hivemq-edge/src/main/java/com/hivemq/combining/model/DataIdentifierReference.java
hivemq-edge/src/main/java/com/hivemq/combining/runtime/DataCombiningPublishService.java
hivemq-edge/src/main/java/com/hivemq/combining/runtime/DataCombiningRuntime.java
hivemq-edge/src/main/java/com/hivemq/combining/runtime/SourceSanitizer.java

**card**: https://hivemq.kanbanize.com/ctrl_board/57/cards/31203/details/
**tests**: https://github.com/hivemq/hivemq-edge-test/pull/163

Bugfix/31203 Combiner fails to output a message if other sources are missing

---

hivemq-edge/src/main/java/com/hivemq/http/HttpStatus.java

**card**: https://hivemq.kanbanize.com/ctrl_board/57/cards/31280/details/

Add http status response

---

hivemq-edge/src/main/java/com/hivemq/bridge/BridgeService.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/config/SimulationSpecificAdapterConfig.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/config/SimulationToMqttConfig.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/tag/SimulationTag.java
hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/tag/SimulationTagDefinition.java
hivemq-edge/src/main/java/com/hivemq/persistence/mappings/NorthboundMapping.java
hivemq-edge/src/main/java/com/hivemq/persistence/mappings/SouthboundMapping.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterConfig.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/config/EipSpecificAdapterConfig.java
modules/hivemq-edge-module-etherip/src/main/java/com/hivemq/edge/adapters/etherip/config/EipToMqttConfig.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/config/FileSpecificAdapterConfig.java
modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/config/FileToMqttConfig.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/config/HttpSpecificAdapterConfig.java
modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/config/http2mqtt/HttpToMqttMapping.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/ModbusSpecificAdapterConfig.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/ModbusToMqttConfig.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/OpcUaSpecificAdapterConfig.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/opcua2mqtt/OpcUaToMqttConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/config/ADSSpecificAdapterConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/config/ADSToMqttConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/config/S7SpecificAdapterConfig.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/config/S7ToMqttConfig.java

**Motivation**
Fix issues around hot reloading of adapters.
**Changes**
- Hot reload was looking at the wrong file to trigger the reload. 
- Fixed that updates would always result in start/stop even when the config hadn't changes

 Hot reloading fixes

---

hivemq-edge/src/main/java/com/hivemq/bridge/BridgeService.java
hivemq-edge/src/main/java/com/hivemq/bridge/config/BridgeTls.java
hivemq-edge/src/main/java/com/hivemq/bridge/config/BridgeWebsocketConfig.java
hivemq-edge/src/main/java/com/hivemq/bridge/config/LocalSubscription.java
hivemq-edge/src/main/java/com/hivemq/bridge/config/MqttBridge.java
hivemq-edge/src/main/java/com/hivemq/bridge/config/RemoteSubscription.java
hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/BridgeMqttClient.java
hivemq-edge/src/main/java/com/hivemq/mqtt/services/PublishDistributorImpl.java

**Motivation**
Resolves #31832
**Changes**
BridgeService was missing the logic to restart a bridge that already existed but received a new config.

Fixed, bridges not updating when config changed for an existing bridge

---

ext/hivemq-edge-openapi-2025.7-SNAPSHOT.yaml

The new snapshot file was not committed as part of the version upgrade. This fix will close the issue.

fix: Add OpenAPI 2025.7 Snapshot

---

hivemq-edge/src/main/java/com/hivemq/configuration/entity/EntityValidatable.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/NorthboundMappingEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/ProtocolAdapterEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/SouthboundMappingEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/TagEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/fieldmapping/FieldMappingEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/fieldmapping/InstructionEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/combining/DataIdentifierReferenceEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/migration/ConfigurationMigrator.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ProtocolAdapterExtractorTest.java
hivemq-edge/src/test/java/com/hivemq/edge/modules/adapters/simulation/config/legacy/LegacySimulationProtocolAdapterConfigTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/32079/details/

fix: Hot-reload: Invalid Mappings should Fail the Validation

---

build.gradle.kts

**Motivation**
https://hivemq.kanbanize.com/ctrl_board/41/cards/31827/details/
This is what the new coverage looks like btw.  https://jenkins.cicd.pd.hmq.dev/job/HiveMQ4/job/hivemq-edge-composite/job/add-coverage-plugin%252Flatest/9/coverage/ 
**Changes**

Add `jacocoTestReport` task

---

ext/openAPI/README.md
hivemq-edge/src/frontend/package.json
hivemq-edge/src/frontend/src/api/__generated__/models/TypeIdentifier.ts
hivemq-edge/src/frontend/src/modules/EventLog/components/SourceLink.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/table/SourceCombiner.spec.cy.tsx
hivemq-edge/src/frontend/src/modules/EventLog/components/table/SourceCombiner.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/31411/details/
A simple update from the changes made to the OpenAPI specs. The change was anticipated in the code, the PR fixes the references to the types/

fix(31411): Update openAPI stubs

---

hivemq-edge/src/main/java/com/hivemq/combining/runtime/DataCombinerManager.java
hivemq-edge/src/test/java/com/hivemq/combining/DataCombinerManagerTest.java
hivemq-edge/src/test/java/com/hivemq/combining/DataCombiningExtractorTest.java
modules/hivemq-edge-module-etherip/build.gradle.kts
modules/hivemq-edge-module-file/build.gradle.kts
modules/hivemq-edge-module-http/build.gradle.kts
modules/hivemq-edge-module-modbus/build.gradle.kts
modules/hivemq-edge-module-mtconnect/build.gradle.kts
modules/hivemq-edge-module-opcua/build.gradle.kts
modules/hivemq-edge-module-plc4x/build.gradle.kts

**Motivation**
Resolves #32561
**Changes**
- Fix DataCombinerManager incorrectly logging a failure during deletion
- Add tests for the DataCombinerManager

DataCombinerManager was incorrectly logging a deletiong error

---

ext/hivemq-edge-openapi-2025.7.yaml

Added missing spec

---

.github/workflows/check-backend.yml
.github/workflows/check-frontend.yml
.github/workflows/check.yml
hivemq-edge/build.gradle.kts

**Motivation**
Resolves #32593
**Changes**
Separate the git actions for better performance.

Split check.yml

---

.github/workflows/check-backend.yml
gradle/libs.versions.toml
modules/hivemq-edge-module-mtconnect/build.gradle.kts

https://hivemq.kanbanize.com/ctrl_board/57/cards/32710/details/

chore: Reference external MTConnect protocol library

---

hivemq-edge/settings.gradle.kts

https://hivemq.kanbanize.com/ctrl_board/57/cards/32710/details/

fix: Remove MTConnect protocol from settings.gradle.kts

---

build.gradle.kts
hivemq-edge/build.gradle.kts

**Motivation**
We had issues with missing tasks and classes not being built correctly when run in idea.
**Changes**
- Exclude frontend from task generation where requried
- Add idea module

Exclude missing tasks for frontend and add idea plugin

---

.github/workflows/check.yml

see https://hivemq.kanbanize.com/ctrl_board/57/cards/32972/details/

chore(32972): add github to BE and FE filters

---

build.gradle.kts

https://hivemq.kanbanize.com/ctrl_board/57/cards/33183/details/

fix: Exclude frontend from task check

---

ext/hivemq-edge-openapi-2025.9-SNAPSHOT.yaml
ext/openAPI/components/schemas/InterpolationVariableList.yaml

https://hivemq.kanbanize.com/ctrl_board/57/cards/33977/details/

feat: Add DataHub interpolation variables

---

build.gradle.kts
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaClientConnection.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaEndpointFilter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/ParsedConfig.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/OpcUaSpecificAdapterConfig.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/Tls.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/opcua2mqtt/OpcUaToMqttConfig.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterAuthTest.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/config/OpcUaProtocolAdapterConfigTest.java
modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/northbound/AbstractOpcUaPayloadConverterTest.java

**Motivation**
Equality wasn't correctly implemented for the OPC UA config.

Fixed reload not working

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/config/Tls.java

**Motivation**
Resolves test breaking because of changed documentation (config titself is not affected)

Fixing naing changes that slipped through

---

build.gradle.kts

https://hivemq.kanbanize.com/ctrl_board/22/cards/35039/details/

Update eclipse-temurin to 3aa7f6dc20dcf61b7ca765cae9a425439933bf0367923c2d9ba80bc60cfa9680

---

ext/openAPI/paths/pulse/activation_token.yaml

https://hivemq.kanbanize.com/ctrl_board/57/cards/35468/details/

refactor: Update openapi spec for delete/update a token

---

ext/hivemq-edge-openapi-2025.14-SNAPSHOT.yaml
ext/openAPI/components/schemas/Capability.yaml
ext/openAPI/openapi.yaml
hivemq-edge/src/main/java/com/hivemq/combining/model/DataIdentifierReference.java
hivemq-edge/src/main/java/com/hivemq/edge/HiveMQCapabilityService.java
hivemq-edge/src/main/java/com/hivemq/edge/impl/capability/CapabilityServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/http/HttpStatus.java
hivemq-edge/src/main/java/com/hivemq/pulse/status/StatusProvider.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/35468/details/
https://hivemq.kanbanize.com/ctrl_board/57/cards/35458/details/

feat: Add Pulse activation

---

modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaClientConnection.java

**Motivation**
Resolves #35532
**Changes**
Replace broken logic for URI rewriting with the original filter.

Fixing overrideUri since it was broken during the rework

---

modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/config/ModbusSpecificAdapterConfig.java
modules/hivemq-edge-module-modbus/src/main/resources/modbus-adapter-ui-schema.json

**Motivation**
Resolves #35596
**Changes**
Adding id-property required by the UI.

Id was missing in the modbus schema

---

hivemq-edge-openapi/openapi/components/schemas/Asset.yaml
hivemq-edge-openapi/openapi/paths/pulse/managed-assets.yaml
hivemq-edge-openapi/openapi/paths/pulse/managed-assets_{assetId}.yaml

https://hivemq.kanbanize.com/ctrl_board/57/cards/35469/details/

fix: Set schema to readonly

---

ext/hivemq-edge-openapi-2025.14-SNAPSHOT.yaml
ext/openAPI/components/schemas/NorthboundMapping.yaml
hivemq-edge/src/main/java/com/hivemq/api/model/mappings/northbound/NorthboundMappingModel.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/GatewayResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/NorthboundMappingEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/ProtocolAdapterEntity.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/TagEntity.java
hivemq-edge/src/main/java/com/hivemq/persistence/mappings/NorthboundMapping.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterConfigConverter.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterUtils.java
hivemq-edge/src/test/java/com/hivemq/api/model/mappings/northbound/NorthboundMappingModelTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ConfigFileReaderTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ProtocolAdapterExtractorTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/writer/ConfigFileWriterTest.java
hivemq-edge/src/test/java/com/hivemq/edge/modules/adapters/simulation/config/SimulationProtocolAdapterConfigTest.java
hivemq-edge/src/test/resources/test-config.xml
modules/hivemq-edge-module-http/src/test/java/com/hivemq/edge/adapters/http/config/HttpProtocolAdapterConfigTest.java

**card**: https://hivemq.kanbanize.com/ctrl_board/57/cards/35615/details/

Add missing property to NorthboundMapping

---

hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java

**Motivation**
The FileWriter for writing config files to disk wasn't closed properly.

Closing FileWriter in ConfigFileReaderWriter

---

hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java
modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaClientConnection.java
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java
modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xDataSample.java

**Motivation**
Resolves #35799
**Changes**
Resolve broken test cases for async rework

Fix remining tests

---

hivemq-edge-frontend/src/api/hooks/useDomainModel/useGetCombinedEntities.spec.ts
hivemq-edge-frontend/src/api/hooks/useDomainModel/useGetCombinedEntities.ts
hivemq-edge-frontend/src/components/PaginatedTable/PaginatedTable.spec.cy.tsx
hivemq-edge-frontend/src/components/PaginatedTable/components/TableToolBar.spec.cy.tsx
hivemq-edge-frontend/src/components/PaginatedTable/components/TableToolBar.tsx
hivemq-edge-frontend/src/modules/Pulse/components/assets/ManagedAssetDrawer.spec.cy.tsx
hivemq-edge-frontend/src/modules/Pulse/components/widgets/MappingTargetWidget.spec.cy.tsx
hivemq-edge-frontend/src/modules/Workspace/components/nodes/NodePulse.tsx

See https://hivemq.kanbanize.com/ctrl_board/57/cards/35995/details/
The PR fixes a bug with the aggregation of requests required to extract tags and topic filters from their sources.
It also fixes two small accessibility issues and a few tests

feat(35995): Fix bug with the fetching of combined entities 

---

.github/workflows/snyk-push.yml
hivemq-edge/build.gradle.kts
settings.gradle.kts

Related to: https://github.com/hivemq/hivemq-edge-composite/pull/83

Update to Develocity

---

hivemq-edge/src/main/java/com/hivemq/pulse/utils/PulseAgentAssetUtils.java
hivemq-edge/src/test/java/com/hivemq/pulse/utils/PulseAgentAssetUtilsTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/36289/details/

fix: Fix wrong mappin id calculation in resolveDiff()

---

hivemq-edge/src/main/java/com/hivemq/bootstrap/factories/HandlerResult.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/services/AfterHiveMQStartBootstrapServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/services/CompleteBootstrapService.java
hivemq-edge/src/main/java/com/hivemq/bootstrap/services/CompleteBootstrapServiceImpl.java
hivemq-edge/src/main/java/com/hivemq/mqtt/services/PrePublishProcessorServiceImpl.java

https://hivemq.kanbanize.com/ctrl_board/91/cards/36135/details/

Message rerouting

---

ext/hivemq-edge-openapi-2025.16-SNAPSHOT.yaml
hivemq-edge-openapi/openapi/components/schemas/NorthboundMapping.yaml
hivemq-edge/src/main/java/com/hivemq/api/model/mappings/northbound/NorthboundMappingModel.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/NorthboundMappingEntity.java
hivemq-edge/src/main/java/com/hivemq/persistence/mappings/NorthboundMapping.java
hivemq-edge/src/test/java/com/hivemq/api/model/mappings/northbound/NorthboundMappingModelTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ProtocolAdapterExtractorTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/writer/AbstractConfigWriterTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/writer/ConfigurationServiceSyncTest.java
hivemq-edge/src/test/java/com/hivemq/edge/modules/adapters/simulation/config/SimulationProtocolAdapterConfigTest.java
hivemq-edge/src/test/resources/configs/simulation/simulation-adapter-full-config.xml
hivemq-edge/src/test/resources/test-config.xml
modules/hivemq-edge-module-etherip/src/test/java/com/hivemq/edge/adapters/etherip/config/EipProtocolAdapterConfigTest.java
modules/hivemq-edge-module-etherip/src/test/resources/eip-adapter-full-config.xml
modules/hivemq-edge-module-file/src/test/java/com/hivemq/edge/adapters/file/config/FileProtocolAdapterConfigTest.java
modules/hivemq-edge-module-file/src/test/resources/file-adapter-full-config.xml
modules/hivemq-edge-module-modbus/src/test/java/com/hivemq/edge/adapters/modbus/config/ModbusProtocolAdapterConfigTest.java
modules/hivemq-edge-module-modbus/src/test/resources/modbus-adapter-full-config.xml
modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
modules/hivemq-edge-module-plc4x/src/test/java/com/hivemq/edge/adapters/plc4x/types/ads/config/ADSProtocolAdapterConfigTest.java
modules/hivemq-edge-module-plc4x/src/test/java/com/hivemq/edge/adapters/plc4x/types/siemens/config/S7ProtocolAdapterConfigTest.java
modules/hivemq-edge-module-plc4x/src/test/resources/ads-adapter-full-config.xml
modules/hivemq-edge-module-plc4x/src/test/resources/s7-adapter-full-config.xml

**Motivation**
Resolves #36384
**Changes**
Remove an API-option which was accidentally added back to the API.

Remove messageHandlingOptions which were accidentally added back to the API

---

hivemq-edge/src/main/java/com/hivemq/api/errors/pulse/EmptyMappingsForAssetMapperError.java
hivemq-edge/src/main/java/com/hivemq/api/errors/pulse/EmptySourcesForAssetMapperError.java
hivemq-edge/src/main/java/com/hivemq/api/errors/pulse/MissingEntityTypePulseAgentForAssetMapperError.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/PulseApiImpl.java
hivemq-edge/src/main/java/com/hivemq/combining/model/DataCombiner.java
hivemq-edge/src/main/java/com/hivemq/combining/model/DataCombining.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/AssetMappingExtractor.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplAddAssetMapperTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplDeleteManagedAssetTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/36485/details/

fix: Fix validation

---

hivemq-edge/src/main/java/com/hivemq/configuration/entity/adapter/NorthboundMappingEntity.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/ProtocolAdapterExtractorTest.java
hivemq-edge/src/test/java/com/hivemq/extensions/services/executor/ManagedExecutorServicePerExtensionTest.java
hivemq-edge/src/test/resources/configs/simulation/simulation-adapter-full-config.xml
hivemq-edge/src/test/resources/test-config.xml
modules/hivemq-edge-module-etherip/src/test/resources/eip-adapter-full-config.xml
modules/hivemq-edge-module-file/src/test/resources/file-adapter-full-config.xml
modules/hivemq-edge-module-modbus/src/test/resources/modbus-adapter-full-config.xml
modules/hivemq-edge-module-plc4x/src/test/resources/ads-adapter-full-config.xml
modules/hivemq-edge-module-plc4x/src/test/resources/s7-adapter-full-config.xml

card: https://hivemq.kanbanize.com/ctrl_board/57/cards/36535/details/

Restore messageHandlingOptions to northboundMapping config, ignoring the setting

---

hivemq-edge/src/main/java/com/hivemq/api/errors/pulse/DuplicatedManagedAssetIdError.java
hivemq-edge/src/main/java/com/hivemq/api/resources/impl/PulseApiImpl.java
hivemq-edge/src/main/java/com/hivemq/combining/model/DataCombiner.java
hivemq-edge/src/main/java/com/hivemq/combining/model/DataCombining.java
hivemq-edge/src/main/java/com/hivemq/combining/model/DataIdentifierReference.java
hivemq-edge/src/main/java/com/hivemq/configuration/reader/AssetMappingExtractor.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/AbstractPulseApiImplTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplAddAssetMapperTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplGetAssetMapperInstructionsTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplGetManagedAssetsTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplUpdateAssetMapperTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplUpdateManagedAssetTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/36687/details/

fix: At most one destination per asset

---

hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplAddManagedAssetTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplUpdateManagedAssetTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/36520/details/

test: Add validation for asset mapping update during asset update

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/PulseApiImpl.java
hivemq-edge/src/main/java/com/hivemq/configuration/entity/pulse/PulseAssetEntity.java
hivemq-edge/src/main/java/com/hivemq/pulse/asset/PulseAgentAssetMapping.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplAddAssetMapperTest.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplUpdateManagedAssetTest.java
hivemq-edge/src/test/java/com/hivemq/configuration/reader/PulseExtractorTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/36520/details/

fix: Patch addAssetMapper to allow updating asset mapping id

---

hivemq-edge/src/main/java/com/hivemq/api/resources/impl/PulseApiImpl.java
hivemq-edge/src/test/java/com/hivemq/api/resources/impl/pulse/PulseApiImplAddAssetMapperTest.java

https://hivemq.kanbanize.com/ctrl_board/57/cards/36520/details/

fix: Remove check for empty sources, mappings

---

hivemq-edge-frontend/src/modules/Mappings/CombinerMappingManager.tsx

fix(36963): revert
